"""RAG service initial schema.

Revision ID: df0865eb01ae
Revises:
Create Date: 2026-08-10

Two things here are hand-written on top of what autogenerate produced,
because autogenerate cannot know either:

- ``CREATE EXTENSION IF NOT EXISTS vector`` runs first. Without it the
  ``embedding_vectors.vector`` column cannot be created at all, and the
  failure is an opaque "type vector does not exist" rather than anything
  pointing at the extension. The compose stack runs
  ``pgvector/pgvector:pg17``, so the extension is present to be enabled
  -- verified live as pgvector 0.8.5.
- ``import pgvector.sqlalchemy`` is added by hand. Autogenerate emits
  ``pgvector.sqlalchemy.vector.VECTOR(dim=1536)`` in the column
  definition but never adds the import for it, so the generated file
  raises ``NameError`` on the first run. The same correction
  ai-assistant-service's own initial migration documents.

**No ANN index is created here, deliberately.** An ``ivfflat`` or
``hnsw`` index built over an empty or small table is both slower and
less accurate than the sequential scan it replaces -- ivfflat in
particular needs representative data present at build time to pick its
cluster centroids. Index creation is therefore an explicit operation
against a corpus of known size; see ``app/indexing/`` and the
``vector_indexes`` table, which exists precisely so "which index exists,
and is it built?" is a recorded fact rather than a guess.
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0865eb01ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_models',
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usd_per_1k_tokens', sa.Float(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_embedded', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'model_name', 'model_version', name='uq_embedding_model')
    )
    op.create_index('ix_embedding_model_default', 'embedding_models', ['is_default'], unique=False)
    op.create_index(op.f('ix_embedding_models_is_default'), 'embedding_models', ['is_default'], unique=False)
    op.create_index(op.f('ix_embedding_models_provider'), 'embedding_models', ['provider'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=True),
    sa.Column('credential_reference', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_cursor', sa.String(length=512), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('default_classification', sa.String(length=16), nullable=False),
    sa.Column('default_tags', sa.JSON(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('chunk_strategy', sa.String(length=24), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_knowledge_source_slug')
    )
    op.create_index('ix_knowledge_source_kind', 'knowledge_sources', ['source_kind'], unique=False)
    op.create_index('ix_knowledge_source_sync_status', 'knowledge_sources', ['sync_status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_is_enabled'), 'knowledge_sources', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_slug'), 'knowledge_sources', ['slug'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_source_kind'), 'knowledge_sources', ['source_kind'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_sync_status'), 'knowledge_sources', ['sync_status'], unique=False)
    op.create_table('rag_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_audit_action', 'rag_audit', ['action'], unique=False)
    op.create_index(op.f('ix_rag_audit_actor_id'), 'rag_audit', ['actor_id'], unique=False)
    op.create_index('ix_rag_audit_entity', 'rag_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_rag_audit_entity_id'), 'rag_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_rag_audit_occurred_at'), 'rag_audit', ['occurred_at'], unique=False)
    op.create_table('rag_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_report_kind', 'rag_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_rag_reports_kind'), 'rag_reports', ['kind'], unique=False)
    op.create_table('rag_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('documents_total', sa.Integer(), nullable=False),
    sa.Column('documents_indexed', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('vectors_total', sa.Integer(), nullable=False),
    sa.Column('index_size_bytes', sa.Integer(), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('retrievals_empty', sa.Integer(), nullable=False),
    sa.Column('retrievals_denied', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('average_result_count', sa.Float(), nullable=True),
    sa.Column('tokens_embedded', sa.Integer(), nullable=False),
    sa.Column('embedding_cost_usd', sa.Float(), nullable=False),
    sa.Column('search_accuracy', sa.Float(), nullable=True),
    sa.Column('top_sources', sa.JSON(), nullable=False),
    sa.Column('top_documents', sa.JSON(), nullable=False),
    sa.Column('unanswered_queries', sa.JSON(), nullable=False),
    sa.Column('by_strategy', sa.JSON(), nullable=False),
    sa.Column('by_source_kind', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_statistic_window', 'rag_statistics', ['window_start', 'window_end'], unique=False)
    op.create_table('retrieval_queries',
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('fusion_method', sa.String(length=16), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('project_scope_id', sa.Uuid(), nullable=True),
    sa.Column('caller_roles', sa.JSON(), nullable=False),
    sa.Column('metadata_filters', sa.JSON(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('denied_count', sa.Integer(), nullable=False),
    sa.Column('vector_weight', sa.Float(), nullable=False),
    sa.Column('keyword_weight', sa.Float(), nullable=False),
    sa.Column('graph_weight', sa.Float(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('embedding_ms', sa.Float(), nullable=True),
    sa.Column('search_ms', sa.Float(), nullable=True),
    sa.Column('rerank_ms', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_queries_executed_at'), 'retrieval_queries', ['executed_at'], unique=False)
    op.create_index(op.f('ix_retrieval_queries_outcome'), 'retrieval_queries', ['outcome'], unique=False)
    op.create_index(op.f('ix_retrieval_queries_requested_by'), 'retrieval_queries', ['requested_by'], unique=False)
    op.create_index(op.f('ix_retrieval_queries_strategy'), 'retrieval_queries', ['strategy'], unique=False)
    op.create_index('ix_retrieval_query_executed_at', 'retrieval_queries', ['executed_at'], unique=False)
    op.create_index('ix_retrieval_query_outcome', 'retrieval_queries', ['outcome'], unique=False)
    op.create_index('ix_retrieval_query_strategy', 'retrieval_queries', ['strategy'], unique=False)
    op.create_table('vector_indexes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('store_provider', sa.String(length=24), nullable=False),
    sa.Column('embedding_provider', sa.String(length=24), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('index_method', sa.String(length=32), nullable=True),
    sa.Column('index_parameters', sa.JSON(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('last_built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_vector_index_name')
    )
    op.create_index('ix_vector_index_provider', 'vector_indexes', ['store_provider'], unique=False)
    op.create_index(op.f('ix_vector_indexes_store_provider'), 'vector_indexes', ['store_provider'], unique=False)
    op.create_table('documents',
    sa.Column('knowledge_source_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('project_scope_id', sa.Uuid(), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('allowed_tags', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('storage_bucket', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('source_uri', sa.String(length=2048), nullable=True),
    sa.Column('current_version_number', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('last_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_checksum', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('ingested_by', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_document_external_id')
    )
    op.create_index('ix_document_classification', 'documents', ['classification'], unique=False)
    op.create_index('ix_document_source_kind', 'documents', ['source_kind'], unique=False)
    op.create_index('ix_document_status', 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_classification'), 'documents', ['classification'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_source_id'), 'documents', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_documents_project_scope_id'), 'documents', ['project_scope_id'], unique=False)
    op.create_index(op.f('ix_documents_source_kind'), 'documents', ['source_kind'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_metadata',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('is_extracted', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'key', name='uq_document_metadata_key')
    )
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=False)
    op.create_index('ix_document_metadata_key_value', 'document_metadata', ['key', 'value'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('parse_duration_ms', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version_number')
    )
    op.create_index('ix_document_version_current', 'document_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_versions_checksum'), 'document_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_table('indexing_jobs',
    sa.Column('knowledge_source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('documents_total', sa.Integer(), nullable=False),
    sa.Column('documents_succeeded', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('vectors_created', sa.Integer(), nullable=False),
    sa.Column('tokens_embedded', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indexing_job_priority', 'indexing_jobs', ['priority'], unique=False)
    op.create_index('ix_indexing_job_scheduled_at', 'indexing_jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_indexing_job_status', 'indexing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_document_id'), 'indexing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_kind'), 'indexing_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_knowledge_source_id'), 'indexing_jobs', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_priority'), 'indexing_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_scheduled_at'), 'indexing_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_status'), 'indexing_jobs', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_kind', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=1024), nullable=True),
    sa.Column('heading', sa.String(length=512), nullable=True),
    sa.Column('overlap_tokens', sa.Integer(), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('entity_keys', sa.JSON(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'sequence', name='uq_chunk_sequence')
    )
    op.create_index('ix_chunk_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_chunk_embedded', 'document_chunks', ['is_embedded'], unique=False)
    op.create_index('ix_chunk_kind', 'document_chunks', ['chunk_kind'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_kind'), 'document_chunks', ['chunk_kind'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_is_embedded'), 'document_chunks', ['is_embedded'], unique=False)
    op.create_table('embedding_vectors',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_chunk_id', 'provider', 'model_name', name='uq_embedding_vector_chunk_model')
    )
    op.create_index('ix_embedding_vector_document', 'embedding_vectors', ['document_id'], unique=False)
    op.create_index('ix_embedding_vector_model', 'embedding_vectors', ['model_name'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_content_hash'), 'embedding_vectors', ['content_hash'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_document_chunk_id'), 'embedding_vectors', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_document_id'), 'embedding_vectors', ['document_id'], unique=False)
    op.create_index(op.f('ix_embedding_vectors_model_name'), 'embedding_vectors', ['model_name'], unique=False)
    op.create_table('reranking_results',
    sa.Column('retrieval_query_id', sa.Uuid(), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('rank_before', sa.Integer(), nullable=False),
    sa.Column('rank_after', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=False),
    sa.Column('score_after', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_query_id'], ['retrieval_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reranking_result_method', 'reranking_results', ['method'], unique=False)
    op.create_index('ix_reranking_result_query', 'reranking_results', ['retrieval_query_id'], unique=False)
    op.create_index(op.f('ix_reranking_results_document_chunk_id'), 'reranking_results', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_reranking_results_method'), 'reranking_results', ['method'], unique=False)
    op.create_index(op.f('ix_reranking_results_retrieval_query_id'), 'reranking_results', ['retrieval_query_id'], unique=False)
    op.create_table('retrieval_feedback',
    sa.Column('retrieval_query_id', sa.Uuid(), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retrieval_query_id'], ['retrieval_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_feedback_document_chunk_id'), 'retrieval_feedback', ['document_chunk_id'], unique=False)
    op.create_index('ix_retrieval_feedback_query', 'retrieval_feedback', ['retrieval_query_id'], unique=False)
    op.create_index(op.f('ix_retrieval_feedback_retrieval_query_id'), 'retrieval_feedback', ['retrieval_query_id'], unique=False)
    op.create_index(op.f('ix_retrieval_feedback_verdict'), 'retrieval_feedback', ['verdict'], unique=False)
    op.create_table('retrieval_results',
    sa.Column('retrieval_query_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('vector_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('graph_score', sa.Float(), nullable=True),
    sa.Column('vector_rank', sa.Integer(), nullable=True),
    sa.Column('keyword_rank', sa.Integer(), nullable=True),
    sa.Column('graph_rank', sa.Integer(), nullable=True),
    sa.Column('included_in_context', sa.Boolean(), nullable=False),
    sa.Column('citation_label', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_query_id'], ['retrieval_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_result_chunk', 'retrieval_results', ['document_chunk_id'], unique=False)
    op.create_index('ix_retrieval_result_query_rank', 'retrieval_results', ['retrieval_query_id', 'rank'], unique=False)
    op.create_index(op.f('ix_retrieval_results_document_chunk_id'), 'retrieval_results', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_retrieval_results_document_id'), 'retrieval_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_retrieval_results_retrieval_query_id'), 'retrieval_results', ['retrieval_query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_results_retrieval_query_id'), table_name='retrieval_results')
    op.drop_index(op.f('ix_retrieval_results_document_id'), table_name='retrieval_results')
    op.drop_index(op.f('ix_retrieval_results_document_chunk_id'), table_name='retrieval_results')
    op.drop_index('ix_retrieval_result_query_rank', table_name='retrieval_results')
    op.drop_index('ix_retrieval_result_chunk', table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index(op.f('ix_retrieval_feedback_verdict'), table_name='retrieval_feedback')
    op.drop_index(op.f('ix_retrieval_feedback_retrieval_query_id'), table_name='retrieval_feedback')
    op.drop_index('ix_retrieval_feedback_query', table_name='retrieval_feedback')
    op.drop_index(op.f('ix_retrieval_feedback_document_chunk_id'), table_name='retrieval_feedback')
    op.drop_table('retrieval_feedback')
    op.drop_index(op.f('ix_reranking_results_retrieval_query_id'), table_name='reranking_results')
    op.drop_index(op.f('ix_reranking_results_method'), table_name='reranking_results')
    op.drop_index(op.f('ix_reranking_results_document_chunk_id'), table_name='reranking_results')
    op.drop_index('ix_reranking_result_query', table_name='reranking_results')
    op.drop_index('ix_reranking_result_method', table_name='reranking_results')
    op.drop_table('reranking_results')
    op.drop_index(op.f('ix_embedding_vectors_model_name'), table_name='embedding_vectors')
    op.drop_index(op.f('ix_embedding_vectors_document_id'), table_name='embedding_vectors')
    op.drop_index(op.f('ix_embedding_vectors_document_chunk_id'), table_name='embedding_vectors')
    op.drop_index(op.f('ix_embedding_vectors_content_hash'), table_name='embedding_vectors')
    op.drop_index('ix_embedding_vector_model', table_name='embedding_vectors')
    op.drop_index('ix_embedding_vector_document', table_name='embedding_vectors')
    op.drop_table('embedding_vectors')
    op.drop_index(op.f('ix_document_chunks_is_embedded'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_kind'), table_name='document_chunks')
    op.drop_index('ix_chunk_kind', table_name='document_chunks')
    op.drop_index('ix_chunk_embedded', table_name='document_chunks')
    op.drop_index('ix_chunk_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_indexing_jobs_status'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_scheduled_at'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_priority'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_knowledge_source_id'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_kind'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_document_id'), table_name='indexing_jobs')
    op.drop_index('ix_indexing_job_status', table_name='indexing_jobs')
    op.drop_index('ix_indexing_job_scheduled_at', table_name='indexing_jobs')
    op.drop_index('ix_indexing_job_priority', table_name='indexing_jobs')
    op.drop_table('indexing_jobs')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_checksum'), table_name='document_versions')
    op.drop_index('ix_document_version_current', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_metadata_key_value', table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_kind'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_scope_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_classification'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_index('ix_document_status', table_name='documents')
    op.drop_index('ix_document_source_kind', table_name='documents')
    op.drop_index('ix_document_classification', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vector_indexes_store_provider'), table_name='vector_indexes')
    op.drop_index('ix_vector_index_provider', table_name='vector_indexes')
    op.drop_table('vector_indexes')
    op.drop_index('ix_retrieval_query_strategy', table_name='retrieval_queries')
    op.drop_index('ix_retrieval_query_outcome', table_name='retrieval_queries')
    op.drop_index('ix_retrieval_query_executed_at', table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_strategy'), table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_requested_by'), table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_outcome'), table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_executed_at'), table_name='retrieval_queries')
    op.drop_table('retrieval_queries')
    op.drop_index('ix_rag_statistic_window', table_name='rag_statistics')
    op.drop_table('rag_statistics')
    op.drop_index(op.f('ix_rag_reports_kind'), table_name='rag_reports')
    op.drop_index('ix_rag_report_kind', table_name='rag_reports')
    op.drop_table('rag_reports')
    op.drop_index(op.f('ix_rag_audit_occurred_at'), table_name='rag_audit')
    op.drop_index(op.f('ix_rag_audit_entity_id'), table_name='rag_audit')
    op.drop_index('ix_rag_audit_entity', table_name='rag_audit')
    op.drop_index(op.f('ix_rag_audit_actor_id'), table_name='rag_audit')
    op.drop_index('ix_rag_audit_action', table_name='rag_audit')
    op.drop_table('rag_audit')
    op.drop_index(op.f('ix_knowledge_sources_sync_status'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_source_kind'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_slug'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_is_enabled'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_source_sync_status', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_source_kind', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_embedding_models_provider'), table_name='embedding_models')
    op.drop_index(op.f('ix_embedding_models_is_default'), table_name='embedding_models')
    op.drop_index('ix_embedding_model_default', table_name='embedding_models')
    op.drop_table('embedding_models')
    # ### end Alembic commands ###
