"""initial schema

Revision ID: fa35edce2ed0
Revises: 
Create Date: 2026-08-14 22:12:32.038173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa35edce2ed0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli_plugins',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('marketplace_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_plugin_name', 'cli_plugins', ['name'], unique=False)
    op.create_index('ix_cli_plugin_status', 'cli_plugins', ['status'], unique=False)
    op.create_index(op.f('ix_cli_plugins_name'), 'cli_plugins', ['name'], unique=False)
    op.create_index(op.f('ix_cli_plugins_status'), 'cli_plugins', ['status'], unique=False)
    op.create_table('cli_profiles',
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('auth_method', sa.String(length=24), nullable=False),
    sa.Column('organization_context', sa.Uuid(), nullable=True),
    sa.Column('project_context', sa.Uuid(), nullable=True),
    sa.Column('region_context', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_profile_name', 'cli_profiles', ['profile_name'], unique=False)
    op.create_index(op.f('ix_cli_profiles_profile_name'), 'cli_profiles', ['profile_name'], unique=False)
    op.create_table('cli_reports',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_report_kind', 'cli_reports', ['kind'], unique=False)
    op.create_index('ix_cli_report_status', 'cli_reports', ['status'], unique=False)
    op.create_index(op.f('ix_cli_reports_kind'), 'cli_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_cli_reports_status'), 'cli_reports', ['status'], unique=False)
    op.create_table('cli_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sdk_download_count', sa.Integer(), nullable=False),
    sa.Column('cli_download_count', sa.Integer(), nullable=False),
    sa.Column('command_execution_count', sa.Integer(), nullable=False),
    sa.Column('plugin_install_count', sa.Integer(), nullable=False),
    sa.Column('auth_success_count', sa.Integer(), nullable=False),
    sa.Column('auth_failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_cli_statistic_window')
    )
    op.create_index('ix_cli_statistic_window', 'cli_statistics', ['window_start'], unique=False)
    op.create_index(op.f('ix_cli_statistics_window_start'), 'cli_statistics', ['window_start'], unique=False)
    op.create_table('cli_updates',
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_update_status', 'cli_updates', ['status'], unique=False)
    op.create_index(op.f('ix_cli_updates_status'), 'cli_updates', ['status'], unique=False)
    op.create_table('cli_versions',
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('api_compatibility_version', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_version_label', 'cli_versions', ['version_label'], unique=False)
    op.create_index(op.f('ix_cli_versions_version_label'), 'cli_versions', ['version_label'], unique=False)
    op.create_table('sdk_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_audit_action', 'sdk_audit', ['action'], unique=False)
    op.create_index('ix_sdk_audit_actor', 'sdk_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sdk_audit_actor_id'), 'sdk_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sdk_audit_occurred_at'), 'sdk_audit', ['occurred_at'], unique=False)
    op.create_index('ix_sdk_audit_time', 'sdk_audit', ['occurred_at'], unique=False)
    op.create_table('sdk_versions',
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('api_compatibility_version', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_version_label', 'sdk_versions', ['version_label'], unique=False)
    op.create_index('ix_sdk_version_language', 'sdk_versions', ['language'], unique=False)
    op.create_index(op.f('ix_sdk_versions_language'), 'sdk_versions', ['language'], unique=False)
    op.create_index(op.f('ix_sdk_versions_version_label'), 'sdk_versions', ['version_label'], unique=False)
    op.create_table('cli_sessions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('auth_method', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['cli_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_session_profile', 'cli_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_cli_sessions_profile_id'), 'cli_sessions', ['profile_id'], unique=False)
    op.create_table('sdk_downloads',
    sa.Column('sdk_version_id', sa.Uuid(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sdk_version_id'], ['sdk_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_download_downloaded_at', 'sdk_downloads', ['downloaded_at'], unique=False)
    op.create_index('ix_sdk_download_sdk_version', 'sdk_downloads', ['sdk_version_id'], unique=False)
    op.create_index(op.f('ix_sdk_downloads_downloaded_at'), 'sdk_downloads', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_sdk_downloads_sdk_version_id'), 'sdk_downloads', ['sdk_version_id'], unique=False)
    op.create_table('sdk_languages',
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('latest_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['latest_version_id'], ['sdk_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_language_catalog_language', 'sdk_languages', ['language'], unique=False)
    op.create_index(op.f('ix_sdk_languages_language'), 'sdk_languages', ['language'], unique=False)
    op.create_table('sdk_packages',
    sa.Column('sdk_version_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_channel', sa.String(length=16), nullable=False),
    sa.Column('package_ref', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sdk_version_id'], ['sdk_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_package_sdk_version', 'sdk_packages', ['sdk_version_id'], unique=False)
    op.create_index(op.f('ix_sdk_packages_sdk_version_id'), 'sdk_packages', ['sdk_version_id'], unique=False)
    op.create_table('sdk_releases',
    sa.Column('sdk_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('breaking_changes', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sdk_version_id'], ['sdk_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sdk_release_sdk_version', 'sdk_releases', ['sdk_version_id'], unique=False)
    op.create_index('ix_sdk_release_status', 'sdk_releases', ['status'], unique=False)
    op.create_index(op.f('ix_sdk_releases_sdk_version_id'), 'sdk_releases', ['sdk_version_id'], unique=False)
    op.create_index(op.f('ix_sdk_releases_status'), 'sdk_releases', ['status'], unique=False)
    op.create_table('cli_usage',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('command_group', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cli_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cli_usage_command_group'), 'cli_usage', ['command_group'], unique=False)
    op.create_index(op.f('ix_cli_usage_executed_at'), 'cli_usage', ['executed_at'], unique=False)
    op.create_index('ix_cli_usage_session', 'cli_usage', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cli_usage_session', table_name='cli_usage')
    op.drop_index(op.f('ix_cli_usage_executed_at'), table_name='cli_usage')
    op.drop_index(op.f('ix_cli_usage_command_group'), table_name='cli_usage')
    op.drop_table('cli_usage')
    op.drop_index(op.f('ix_sdk_releases_status'), table_name='sdk_releases')
    op.drop_index(op.f('ix_sdk_releases_sdk_version_id'), table_name='sdk_releases')
    op.drop_index('ix_sdk_release_status', table_name='sdk_releases')
    op.drop_index('ix_sdk_release_sdk_version', table_name='sdk_releases')
    op.drop_table('sdk_releases')
    op.drop_index(op.f('ix_sdk_packages_sdk_version_id'), table_name='sdk_packages')
    op.drop_index('ix_sdk_package_sdk_version', table_name='sdk_packages')
    op.drop_table('sdk_packages')
    op.drop_index(op.f('ix_sdk_languages_language'), table_name='sdk_languages')
    op.drop_index('ix_sdk_language_catalog_language', table_name='sdk_languages')
    op.drop_table('sdk_languages')
    op.drop_index(op.f('ix_sdk_downloads_sdk_version_id'), table_name='sdk_downloads')
    op.drop_index(op.f('ix_sdk_downloads_downloaded_at'), table_name='sdk_downloads')
    op.drop_index('ix_sdk_download_sdk_version', table_name='sdk_downloads')
    op.drop_index('ix_sdk_download_downloaded_at', table_name='sdk_downloads')
    op.drop_table('sdk_downloads')
    op.drop_index(op.f('ix_cli_sessions_profile_id'), table_name='cli_sessions')
    op.drop_index('ix_cli_session_profile', table_name='cli_sessions')
    op.drop_table('cli_sessions')
    op.drop_index(op.f('ix_sdk_versions_version_label'), table_name='sdk_versions')
    op.drop_index(op.f('ix_sdk_versions_language'), table_name='sdk_versions')
    op.drop_index('ix_sdk_version_language', table_name='sdk_versions')
    op.drop_index('ix_sdk_version_label', table_name='sdk_versions')
    op.drop_table('sdk_versions')
    op.drop_index('ix_sdk_audit_time', table_name='sdk_audit')
    op.drop_index(op.f('ix_sdk_audit_occurred_at'), table_name='sdk_audit')
    op.drop_index(op.f('ix_sdk_audit_actor_id'), table_name='sdk_audit')
    op.drop_index('ix_sdk_audit_actor', table_name='sdk_audit')
    op.drop_index('ix_sdk_audit_action', table_name='sdk_audit')
    op.drop_table('sdk_audit')
    op.drop_index(op.f('ix_cli_versions_version_label'), table_name='cli_versions')
    op.drop_index('ix_cli_version_label', table_name='cli_versions')
    op.drop_table('cli_versions')
    op.drop_index(op.f('ix_cli_updates_status'), table_name='cli_updates')
    op.drop_index('ix_cli_update_status', table_name='cli_updates')
    op.drop_table('cli_updates')
    op.drop_index(op.f('ix_cli_statistics_window_start'), table_name='cli_statistics')
    op.drop_index('ix_cli_statistic_window', table_name='cli_statistics')
    op.drop_table('cli_statistics')
    op.drop_index(op.f('ix_cli_reports_status'), table_name='cli_reports')
    op.drop_index(op.f('ix_cli_reports_kind'), table_name='cli_reports')
    op.drop_index('ix_cli_report_status', table_name='cli_reports')
    op.drop_index('ix_cli_report_kind', table_name='cli_reports')
    op.drop_table('cli_reports')
    op.drop_index(op.f('ix_cli_profiles_profile_name'), table_name='cli_profiles')
    op.drop_index('ix_cli_profile_name', table_name='cli_profiles')
    op.drop_table('cli_profiles')
    op.drop_index(op.f('ix_cli_plugins_status'), table_name='cli_plugins')
    op.drop_index(op.f('ix_cli_plugins_name'), table_name='cli_plugins')
    op.drop_index('ix_cli_plugin_status', table_name='cli_plugins')
    op.drop_index('ix_cli_plugin_name', table_name='cli_plugins')
    op.drop_table('cli_plugins')
    # ### end Alembic commands ###
