"""initial developer portal schema

Revision ID: a17ba000001a
Revises: 
Create Date: 2026-08-17 11:57:16.979995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17ba000001a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('post_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('accepted_comment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_community_post_status', 'community_posts', ['status'], unique=False)
    op.create_index('ix_community_post_user', 'community_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_posts_moderation_status'), 'community_posts', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_community_posts_post_type'), 'community_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_community_posts_status'), 'community_posts', ['status'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_table('developer_bookmarks',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'content_type', 'content_id', name='uq_developer_bookmark')
    )
    op.create_index(op.f('ix_developer_bookmarks_content_id'), 'developer_bookmarks', ['content_id'], unique=False)
    op.create_index(op.f('ix_developer_bookmarks_content_type'), 'developer_bookmarks', ['content_type'], unique=False)
    op.create_index(op.f('ix_developer_bookmarks_user_id'), 'developer_bookmarks', ['user_id'], unique=False)
    op.create_table('developer_favorites',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'content_type', 'content_id', name='uq_developer_favorite')
    )
    op.create_index(op.f('ix_developer_favorites_content_id'), 'developer_favorites', ['content_id'], unique=False)
    op.create_index(op.f('ix_developer_favorites_content_type'), 'developer_favorites', ['content_type'], unique=False)
    op.create_index(op.f('ix_developer_favorites_user_id'), 'developer_favorites', ['user_id'], unique=False)
    op.create_table('developer_profiles',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_developer_profile_user')
    )
    op.create_index(op.f('ix_developer_profiles_user_id'), 'developer_profiles', ['user_id'], unique=False)
    op.create_table('developer_sessions',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_session_status', 'developer_sessions', ['status'], unique=False)
    op.create_index('ix_developer_session_user', 'developer_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_developer_sessions_expires_at'), 'developer_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_developer_sessions_status'), 'developer_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_developer_sessions_user_id'), 'developer_sessions', ['user_id'], unique=False)
    op.create_table('documentation_pages',
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_documentation_page_slug')
    )
    op.create_index('ix_documentation_page_status', 'documentation_pages', ['status'], unique=False)
    op.create_index(op.f('ix_documentation_pages_slug'), 'documentation_pages', ['slug'], unique=False)
    op.create_index(op.f('ix_documentation_pages_status'), 'documentation_pages', ['status'], unique=False)
    op.create_table('graphql_queries',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphql_queries_user_id'), 'graphql_queries', ['user_id'], unique=False)
    op.create_index('ix_graphql_query_user', 'graphql_queries', ['user_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_knowledge_article_slug')
    )
    op.create_index('ix_knowledge_article_category', 'knowledge_articles', ['category'], unique=False)
    op.create_index('ix_knowledge_article_status', 'knowledge_articles', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_slug'), 'knowledge_articles', ['slug'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_status'), 'knowledge_articles', ['status'], unique=False)
    op.create_table('learning_paths',
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tutorial_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_learning_path_slug')
    )
    op.create_index('ix_learning_path_status', 'learning_paths', ['status'], unique=False)
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=False)
    op.create_index(op.f('ix_learning_paths_status'), 'learning_paths', ['status'], unique=False)
    op.create_table('playground_sessions',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('example_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playground_session_status', 'playground_sessions', ['status'], unique=False)
    op.create_index('ix_playground_session_user', 'playground_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_playground_sessions_example_type'), 'playground_sessions', ['example_type'], unique=False)
    op.create_index(op.f('ix_playground_sessions_last_active_at'), 'playground_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_playground_sessions_status'), 'playground_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_playground_sessions_user_id'), 'playground_sessions', ['user_id'], unique=False)
    op.create_table('plugin_submissions',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_ref', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_submission_status', 'plugin_submissions', ['status'], unique=False)
    op.create_index('ix_plugin_submission_user', 'plugin_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_status'), 'plugin_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_user_id'), 'plugin_submissions', ['user_id'], unique=False)
    op.create_table('portal_audit',
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portal_audit_action', 'portal_audit', ['action'], unique=False)
    op.create_index('ix_portal_audit_entity', 'portal_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_portal_audit_entity_id'), 'portal_audit', ['entity_id'], unique=False)
    op.create_index('ix_portal_audit_occurred_at', 'portal_audit', ['occurred_at'], unique=False)
    op.create_table('portal_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portal_report_kind', 'portal_reports', ['kind'], unique=False)
    op.create_index('ix_portal_report_status', 'portal_reports', ['status'], unique=False)
    op.create_index(op.f('ix_portal_reports_kind'), 'portal_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_portal_reports_status'), 'portal_reports', ['status'], unique=False)
    op.create_table('portal_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portal_visit_count', sa.Integer(), nullable=False),
    sa.Column('documentation_view_count', sa.Integer(), nullable=False),
    sa.Column('sdk_download_count', sa.Integer(), nullable=False),
    sa.Column('search_query_count', sa.Integer(), nullable=False),
    sa.Column('tutorial_completion_count', sa.Integer(), nullable=False),
    sa.Column('plugin_publication_count', sa.Integer(), nullable=False),
    sa.Column('community_activity_count', sa.Integer(), nullable=False),
    sa.Column('ai_assistant_usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_portal_statistic_window')
    )
    op.create_index(op.f('ix_portal_statistics_window_start'), 'portal_statistics', ['window_start'], unique=False)
    op.create_table('sample_projects',
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('repository_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_sample_project_slug')
    )
    op.create_index('ix_sample_project_category', 'sample_projects', ['category'], unique=False)
    op.create_index('ix_sample_project_status', 'sample_projects', ['status'], unique=False)
    op.create_index(op.f('ix_sample_projects_category'), 'sample_projects', ['category'], unique=False)
    op.create_index(op.f('ix_sample_projects_slug'), 'sample_projects', ['slug'], unique=False)
    op.create_index(op.f('ix_sample_projects_status'), 'sample_projects', ['status'], unique=False)
    op.create_table('sdk_downloads',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portal_sdk_download_language', 'sdk_downloads', ['language'], unique=False)
    op.create_index('ix_portal_sdk_download_user', 'sdk_downloads', ['user_id'], unique=False)
    op.create_index(op.f('ix_sdk_downloads_downloaded_at'), 'sdk_downloads', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_sdk_downloads_language'), 'sdk_downloads', ['language'], unique=False)
    op.create_index(op.f('ix_sdk_downloads_user_id'), 'sdk_downloads', ['user_id'], unique=False)
    op.create_table('search_index',
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'content_type', 'content_id', name='uq_search_index_entry')
    )
    op.create_index(op.f('ix_search_index_content_id'), 'search_index', ['content_id'], unique=False)
    op.create_index(op.f('ix_search_index_content_type'), 'search_index', ['content_type'], unique=False)
    op.create_index(op.f('ix_search_index_indexed_at'), 'search_index', ['indexed_at'], unique=False)
    op.create_table('tutorials',
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_tutorial_slug')
    )
    op.create_index('ix_tutorial_status', 'tutorials', ['status'], unique=False)
    op.create_index(op.f('ix_tutorials_slug'), 'tutorials', ['slug'], unique=False)
    op.create_index(op.f('ix_tutorials_status'), 'tutorials', ['status'], unique=False)
    op.create_table('webhook_tests',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_test_status', 'webhook_tests', ['status'], unique=False)
    op.create_index('ix_webhook_test_user', 'webhook_tests', ['user_id'], unique=False)
    op.create_index(op.f('ix_webhook_tests_status'), 'webhook_tests', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_tests_user_id'), 'webhook_tests', ['user_id'], unique=False)
    op.create_table('code_snippets',
    sa.Column('sample_project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sample_project_id'], ['sample_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_snippet_sample_project', 'code_snippets', ['sample_project_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('community_post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['community_post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_community_comment_post', 'community_comments', ['community_post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_community_post_id'), 'community_comments', ['community_post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_moderation_status'), 'community_comments', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_community_comments_user_id'), 'community_comments', ['user_id'], unique=False)
    op.create_table('documentation_feedback',
    sa.Column('documentation_page_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['documentation_page_id'], ['documentation_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentation_feedback_documentation_page_id'), 'documentation_feedback', ['documentation_page_id'], unique=False)
    op.create_index('ix_documentation_feedback_page', 'documentation_feedback', ['documentation_page_id'], unique=False)
    op.create_index(op.f('ix_documentation_feedback_user_id'), 'documentation_feedback', ['user_id'], unique=False)
    op.create_table('documentation_versions',
    sa.Column('documentation_page_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['documentation_page_id'], ['documentation_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documentation_version_page', 'documentation_versions', ['documentation_page_id'], unique=False)
    op.create_index(op.f('ix_documentation_versions_documentation_page_id'), 'documentation_versions', ['documentation_page_id'], unique=False)
    op.create_table('plugin_reviews',
    sa.Column('plugin_submission_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_submission_id'], ['plugin_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_review_submission', 'plugin_reviews', ['plugin_submission_id'], unique=False)
    op.create_index(op.f('ix_plugin_reviews_plugin_submission_id'), 'plugin_reviews', ['plugin_submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_reviews_plugin_submission_id'), table_name='plugin_reviews')
    op.drop_index('ix_plugin_review_submission', table_name='plugin_reviews')
    op.drop_table('plugin_reviews')
    op.drop_index(op.f('ix_documentation_versions_documentation_page_id'), table_name='documentation_versions')
    op.drop_index('ix_documentation_version_page', table_name='documentation_versions')
    op.drop_table('documentation_versions')
    op.drop_index(op.f('ix_documentation_feedback_user_id'), table_name='documentation_feedback')
    op.drop_index('ix_documentation_feedback_page', table_name='documentation_feedback')
    op.drop_index(op.f('ix_documentation_feedback_documentation_page_id'), table_name='documentation_feedback')
    op.drop_table('documentation_feedback')
    op.drop_index(op.f('ix_community_comments_user_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_moderation_status'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_community_post_id'), table_name='community_comments')
    op.drop_index('ix_community_comment_post', table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index('ix_code_snippet_sample_project', table_name='code_snippets')
    op.drop_table('code_snippets')
    op.drop_index(op.f('ix_webhook_tests_user_id'), table_name='webhook_tests')
    op.drop_index(op.f('ix_webhook_tests_status'), table_name='webhook_tests')
    op.drop_index('ix_webhook_test_user', table_name='webhook_tests')
    op.drop_index('ix_webhook_test_status', table_name='webhook_tests')
    op.drop_table('webhook_tests')
    op.drop_index(op.f('ix_tutorials_status'), table_name='tutorials')
    op.drop_index(op.f('ix_tutorials_slug'), table_name='tutorials')
    op.drop_index('ix_tutorial_status', table_name='tutorials')
    op.drop_table('tutorials')
    op.drop_index(op.f('ix_search_index_indexed_at'), table_name='search_index')
    op.drop_index(op.f('ix_search_index_content_type'), table_name='search_index')
    op.drop_index(op.f('ix_search_index_content_id'), table_name='search_index')
    op.drop_table('search_index')
    op.drop_index(op.f('ix_sdk_downloads_user_id'), table_name='sdk_downloads')
    op.drop_index(op.f('ix_sdk_downloads_language'), table_name='sdk_downloads')
    op.drop_index(op.f('ix_sdk_downloads_downloaded_at'), table_name='sdk_downloads')
    op.drop_index('ix_portal_sdk_download_user', table_name='sdk_downloads')
    op.drop_index('ix_portal_sdk_download_language', table_name='sdk_downloads')
    op.drop_table('sdk_downloads')
    op.drop_index(op.f('ix_sample_projects_status'), table_name='sample_projects')
    op.drop_index(op.f('ix_sample_projects_slug'), table_name='sample_projects')
    op.drop_index(op.f('ix_sample_projects_category'), table_name='sample_projects')
    op.drop_index('ix_sample_project_status', table_name='sample_projects')
    op.drop_index('ix_sample_project_category', table_name='sample_projects')
    op.drop_table('sample_projects')
    op.drop_index(op.f('ix_portal_statistics_window_start'), table_name='portal_statistics')
    op.drop_table('portal_statistics')
    op.drop_index(op.f('ix_portal_reports_status'), table_name='portal_reports')
    op.drop_index(op.f('ix_portal_reports_kind'), table_name='portal_reports')
    op.drop_index('ix_portal_report_status', table_name='portal_reports')
    op.drop_index('ix_portal_report_kind', table_name='portal_reports')
    op.drop_table('portal_reports')
    op.drop_index('ix_portal_audit_occurred_at', table_name='portal_audit')
    op.drop_index(op.f('ix_portal_audit_entity_id'), table_name='portal_audit')
    op.drop_index('ix_portal_audit_entity', table_name='portal_audit')
    op.drop_index('ix_portal_audit_action', table_name='portal_audit')
    op.drop_table('portal_audit')
    op.drop_index(op.f('ix_plugin_submissions_user_id'), table_name='plugin_submissions')
    op.drop_index(op.f('ix_plugin_submissions_status'), table_name='plugin_submissions')
    op.drop_index('ix_plugin_submission_user', table_name='plugin_submissions')
    op.drop_index('ix_plugin_submission_status', table_name='plugin_submissions')
    op.drop_table('plugin_submissions')
    op.drop_index(op.f('ix_playground_sessions_user_id'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_status'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_last_active_at'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_example_type'), table_name='playground_sessions')
    op.drop_index('ix_playground_session_user', table_name='playground_sessions')
    op.drop_index('ix_playground_session_status', table_name='playground_sessions')
    op.drop_table('playground_sessions')
    op.drop_index(op.f('ix_learning_paths_status'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_index('ix_learning_path_status', table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_knowledge_articles_status'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_slug'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_index('ix_knowledge_article_status', table_name='knowledge_articles')
    op.drop_index('ix_knowledge_article_category', table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index('ix_graphql_query_user', table_name='graphql_queries')
    op.drop_index(op.f('ix_graphql_queries_user_id'), table_name='graphql_queries')
    op.drop_table('graphql_queries')
    op.drop_index(op.f('ix_documentation_pages_status'), table_name='documentation_pages')
    op.drop_index(op.f('ix_documentation_pages_slug'), table_name='documentation_pages')
    op.drop_index('ix_documentation_page_status', table_name='documentation_pages')
    op.drop_table('documentation_pages')
    op.drop_index(op.f('ix_developer_sessions_user_id'), table_name='developer_sessions')
    op.drop_index(op.f('ix_developer_sessions_status'), table_name='developer_sessions')
    op.drop_index(op.f('ix_developer_sessions_expires_at'), table_name='developer_sessions')
    op.drop_index('ix_developer_session_user', table_name='developer_sessions')
    op.drop_index('ix_developer_session_status', table_name='developer_sessions')
    op.drop_table('developer_sessions')
    op.drop_index(op.f('ix_developer_profiles_user_id'), table_name='developer_profiles')
    op.drop_table('developer_profiles')
    op.drop_index(op.f('ix_developer_favorites_user_id'), table_name='developer_favorites')
    op.drop_index(op.f('ix_developer_favorites_content_type'), table_name='developer_favorites')
    op.drop_index(op.f('ix_developer_favorites_content_id'), table_name='developer_favorites')
    op.drop_table('developer_favorites')
    op.drop_index(op.f('ix_developer_bookmarks_user_id'), table_name='developer_bookmarks')
    op.drop_index(op.f('ix_developer_bookmarks_content_type'), table_name='developer_bookmarks')
    op.drop_index(op.f('ix_developer_bookmarks_content_id'), table_name='developer_bookmarks')
    op.drop_table('developer_bookmarks')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_status'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_post_type'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_moderation_status'), table_name='community_posts')
    op.drop_index('ix_community_post_user', table_name='community_posts')
    op.drop_index('ix_community_post_status', table_name='community_posts')
    op.drop_table('community_posts')
    # ### end Alembic commands ###
