"""document intelligence initial schema

Revision ID: 67aed44dbf25
Revises: 
Create Date: 2026-08-12 12:46:32.122193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67aed44dbf25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_audit_action', 'document_audit', ['action'], unique=False)
    op.create_index('ix_di_audit_entity', 'document_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_di_audit_occurred', 'document_audit', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_document_audit_action'), 'document_audit', ['action'], unique=False)
    op.create_index(op.f('ix_document_audit_actor_id'), 'document_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_document_audit_occurred_at'), 'document_audit', ['occurred_at'], unique=False)
    op.create_table('document_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_report_kind', 'document_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_document_reports_kind'), 'document_reports', ['kind'], unique=False)
    op.create_table('document_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('documents_total', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('documents_awaiting_review', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_ocred', sa.Integer(), nullable=False),
    sa.Column('entities_extracted', sa.Integer(), nullable=False),
    sa.Column('tables_extracted', sa.Integer(), nullable=False),
    sa.Column('fields_extracted', sa.Integer(), nullable=False),
    sa.Column('mean_ocr_confidence', sa.Float(), nullable=True),
    sa.Column('mean_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('mean_processing_ms', sa.Float(), nullable=True),
    sa.Column('correction_rate', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('mean_review_ms', sa.Float(), nullable=True),
    sa.Column('by_format', sa.JSON(), nullable=False),
    sa.Column('by_category', sa.JSON(), nullable=False),
    sa.Column('by_status', sa.JSON(), nullable=False),
    sa.Column('by_entity_kind', sa.JSON(), nullable=False),
    sa.Column('most_corrected_fields', sa.JSON(), nullable=False),
    sa.Column('lowest_confidence_documents', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_statistic_window', 'document_statistics', ['window_start'], unique=False)
    op.create_table('documents',
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('document_format', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('storage_bucket', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('source_uri', sa.String(length=2048), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=True),
    sa.Column('requires_ocr', sa.Boolean(), nullable=False),
    sa.Column('ocr_completed', sa.Boolean(), nullable=False),
    sa.Column('mean_ocr_confidence', sa.Float(), nullable=True),
    sa.Column('lowest_page_confidence', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=512), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_duration_ms', sa.Float(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('archive_parent_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['archive_parent_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_di_document_external_id')
    )
    op.create_index('ix_di_document_checksum', 'documents', ['checksum'], unique=False)
    op.create_index('ix_di_document_format', 'documents', ['document_format'], unique=False)
    op.create_index('ix_di_document_status', 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_archive_parent_id'), 'documents', ['archive_parent_id'], unique=False)
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_document_format'), 'documents', ['document_format'], unique=False)
    op.create_index(op.f('ix_documents_duplicate_of_id'), 'documents', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_documents_requires_review'), 'documents', ['requires_review'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_processing_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('current_stage', sa.String(length=24), nullable=True),
    sa.Column('stage_results', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('entities_extracted', sa.Integer(), nullable=False),
    sa.Column('tables_extracted', sa.Integer(), nullable=False),
    sa.Column('fields_extracted', sa.Integer(), nullable=False),
    sa.Column('stages_succeeded', sa.Integer(), nullable=False),
    sa.Column('stages_failed', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_job_document', 'document_processing_jobs', ['document_id'], unique=False)
    op.create_index('ix_di_job_priority', 'document_processing_jobs', ['priority'], unique=False)
    op.create_index('ix_di_job_scheduled', 'document_processing_jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_di_job_status', 'document_processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_document_id'), 'document_processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_priority'), 'document_processing_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_scheduled_at'), 'document_processing_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_status'), 'document_processing_jobs', ['status'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('ocr_engine', sa.String(length=16), nullable=False),
    sa.Column('ocr_languages', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_reprocess', sa.Boolean(), nullable=False),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('produced_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_di_version_number')
    )
    op.create_index('ix_di_version_current', 'document_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_versions_checksum'), 'document_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_table('document_classifications',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('custom_category', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.String(length=512), nullable=True),
    sa.Column('matched_terms', sa.JSON(), nullable=False),
    sa.Column('routed_to', sa.String(length=255), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'category', 'custom_category', name='uq_di_classification')
    )
    op.create_index('ix_di_classification_category', 'document_classifications', ['category'], unique=False)
    op.create_index('ix_di_classification_document', 'document_classifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_classifications_category'), 'document_classifications', ['category'], unique=False)
    op.create_index(op.f('ix_document_classifications_document_id'), 'document_classifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_classifications_document_version_id'), 'document_classifications', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_classifications_is_primary'), 'document_classifications', ['is_primary'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('rotation_degrees', sa.Integer(), nullable=False),
    sa.Column('resolution_dpi', sa.Integer(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=16), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_quality', sa.String(length=16), nullable=True),
    sa.Column('ocr_duration_ms', sa.Float(), nullable=True),
    sa.Column('word_confidences', sa.JSON(), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('has_tables', sa.Boolean(), nullable=False),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.Column('has_signatures', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'page_number', name='uq_di_page_number')
    )
    op.create_index('ix_di_page_document', 'document_pages', ['document_id'], unique=False)
    op.create_index('ix_di_page_quality', 'document_pages', ['ocr_quality'], unique=False)
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_document_version_id'), 'document_pages', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_pages_ocr_quality'), 'document_pages', ['ocr_quality'], unique=False)
    op.create_table('document_reviews',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('triggered_by_confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('corrections_applied', sa.Integer(), nullable=False),
    sa.Column('fields_corrected', sa.JSON(), nullable=False),
    sa.Column('escalated_to', sa.String(length=128), nullable=True),
    sa.Column('escalation_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_review_assignee', 'document_reviews', ['assigned_to'], unique=False)
    op.create_index('ix_di_review_document', 'document_reviews', ['document_id'], unique=False)
    op.create_index('ix_di_review_due', 'document_reviews', ['due_at'], unique=False)
    op.create_index('ix_di_review_status', 'document_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_document_reviews_assigned_to'), 'document_reviews', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_document_reviews_document_id'), 'document_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_reviews_document_version_id'), 'document_reviews', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_reviews_priority'), 'document_reviews', ['priority'], unique=False)
    op.create_index(op.f('ix_document_reviews_status'), 'document_reviews', ['status'], unique=False)
    op.create_table('document_summaries',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('summary_kind', sa.String(length=16), nullable=False),
    sa.Column('section_path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentence_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('source_sentence_indices', sa.JSON(), nullable=False),
    sa.Column('is_extractive', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'summary_kind', 'section_path', name='uq_di_summary_kind')
    )
    op.create_index('ix_di_summary_document', 'document_summaries', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_summaries_document_id'), 'document_summaries', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_summaries_document_version_id'), 'document_summaries', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_summaries_summary_kind'), 'document_summaries', ['summary_kind'], unique=False)
    op.create_table('document_translations',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detected_source', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('glossary_terms_applied', sa.JSON(), nullable=False),
    sa.Column('preserved_terms', sa.JSON(), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('translated_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'target_language', name='uq_di_translation_language')
    )
    op.create_index('ix_di_translation_document', 'document_translations', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_translations_document_id'), 'document_translations', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_translations_document_version_id'), 'document_translations', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_translations_target_language'), 'document_translations', ['target_language'], unique=False)
    op.create_table('document_validation_results',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_kind', sa.String(length=24), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('expected', sa.String(length=512), nullable=True),
    sa.Column('actual', sa.String(length=512), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_validation_document', 'document_validation_results', ['document_id'], unique=False)
    op.create_index('ix_di_validation_outcome', 'document_validation_results', ['outcome'], unique=False)
    op.create_index('ix_di_validation_rule', 'document_validation_results', ['rule_kind'], unique=False)
    op.create_index(op.f('ix_document_validation_results_document_id'), 'document_validation_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_validation_results_document_version_id'), 'document_validation_results', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_validation_results_outcome'), 'document_validation_results', ['outcome'], unique=False)
    op.create_index(op.f('ix_document_validation_results_rule_kind'), 'document_validation_results', ['rule_kind'], unique=False)
    op.create_table('document_entities',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('entity_kind', sa.String(length=24), nullable=False),
    sa.Column('custom_kind', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=512), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('is_redacted', sa.Boolean(), nullable=False),
    sa.Column('entity_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_entity_document', 'document_entities', ['document_id'], unique=False)
    op.create_index('ix_di_entity_kind', 'document_entities', ['entity_kind'], unique=False)
    op.create_index('ix_di_entity_value', 'document_entities', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_document_entities_document_id'), 'document_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_entities_document_page_id'), 'document_entities', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_entities_document_version_id'), 'document_entities', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_entities_entity_kind'), 'document_entities', ['entity_kind'], unique=False)
    op.create_index(op.f('ix_document_entities_normalized_value'), 'document_entities', ['normalized_value'], unique=False)
    op.create_table('document_forms',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('template_match_score', sa.Float(), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=False),
    sa.Column('filled_field_count', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('has_signature', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('form_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'sequence', name='uq_di_form_sequence')
    )
    op.create_index('ix_di_form_document', 'document_forms', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_forms_document_id'), 'document_forms', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_forms_document_page_id'), 'document_forms', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_forms_document_version_id'), 'document_forms', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_forms_template_id'), 'document_forms', ['template_id'], unique=False)
    op.create_table('document_layouts',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=False),
    sa.Column('region_kind', sa.String(length=16), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('left', sa.Float(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=1024), nullable=True),
    sa.Column('region_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_page_id', 'reading_order', name='uq_di_layout_reading_order')
    )
    op.create_index('ix_di_layout_kind', 'document_layouts', ['region_kind'], unique=False)
    op.create_index('ix_di_layout_page', 'document_layouts', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_layouts_document_id'), 'document_layouts', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_layouts_document_page_id'), 'document_layouts', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_layouts_region_kind'), 'document_layouts', ['region_kind'], unique=False)
    op.create_table('document_tables',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('has_header_row', sa.Boolean(), nullable=False),
    sa.Column('has_footer_row', sa.Boolean(), nullable=False),
    sa.Column('has_merged_cells', sa.Boolean(), nullable=False),
    sa.Column('spans_pages', sa.Boolean(), nullable=False),
    sa.Column('first_page_number', sa.Integer(), nullable=True),
    sa.Column('last_page_number', sa.Integer(), nullable=True),
    sa.Column('parent_table_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('cell_confidences', sa.JSON(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('table_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_table_id'], ['document_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'sequence', name='uq_di_table_sequence')
    )
    op.create_index('ix_di_table_document', 'document_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tables_document_id'), 'document_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tables_document_page_id'), 'document_tables', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_tables_document_version_id'), 'document_tables', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_tables_parent_table_id'), 'document_tables', ['parent_table_id'], unique=False)
    op.create_table('document_key_values',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_form_id', sa.Uuid(), nullable=True),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('normalized_key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('field_kind', sa.String(length=16), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('key_confidence', sa.Float(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('left', sa.Float(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_form_id'], ['document_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_di_kv_document', 'document_key_values', ['document_id'], unique=False)
    op.create_index('ix_di_kv_form', 'document_key_values', ['document_form_id'], unique=False)
    op.create_index('ix_di_kv_key', 'document_key_values', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_document_key_values_document_form_id'), 'document_key_values', ['document_form_id'], unique=False)
    op.create_index(op.f('ix_document_key_values_document_id'), 'document_key_values', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_key_values_document_page_id'), 'document_key_values', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_document_key_values_document_version_id'), 'document_key_values', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_key_values_normalized_key'), 'document_key_values', ['normalized_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_key_values_normalized_key'), table_name='document_key_values')
    op.drop_index(op.f('ix_document_key_values_document_version_id'), table_name='document_key_values')
    op.drop_index(op.f('ix_document_key_values_document_page_id'), table_name='document_key_values')
    op.drop_index(op.f('ix_document_key_values_document_id'), table_name='document_key_values')
    op.drop_index(op.f('ix_document_key_values_document_form_id'), table_name='document_key_values')
    op.drop_index('ix_di_kv_key', table_name='document_key_values')
    op.drop_index('ix_di_kv_form', table_name='document_key_values')
    op.drop_index('ix_di_kv_document', table_name='document_key_values')
    op.drop_table('document_key_values')
    op.drop_index(op.f('ix_document_tables_parent_table_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_document_version_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_document_page_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_document_id'), table_name='document_tables')
    op.drop_index('ix_di_table_document', table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_layouts_region_kind'), table_name='document_layouts')
    op.drop_index(op.f('ix_document_layouts_document_page_id'), table_name='document_layouts')
    op.drop_index(op.f('ix_document_layouts_document_id'), table_name='document_layouts')
    op.drop_index('ix_di_layout_page', table_name='document_layouts')
    op.drop_index('ix_di_layout_kind', table_name='document_layouts')
    op.drop_table('document_layouts')
    op.drop_index(op.f('ix_document_forms_template_id'), table_name='document_forms')
    op.drop_index(op.f('ix_document_forms_document_version_id'), table_name='document_forms')
    op.drop_index(op.f('ix_document_forms_document_page_id'), table_name='document_forms')
    op.drop_index(op.f('ix_document_forms_document_id'), table_name='document_forms')
    op.drop_index('ix_di_form_document', table_name='document_forms')
    op.drop_table('document_forms')
    op.drop_index(op.f('ix_document_entities_normalized_value'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_entity_kind'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_version_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_page_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_id'), table_name='document_entities')
    op.drop_index('ix_di_entity_value', table_name='document_entities')
    op.drop_index('ix_di_entity_kind', table_name='document_entities')
    op.drop_index('ix_di_entity_document', table_name='document_entities')
    op.drop_table('document_entities')
    op.drop_index(op.f('ix_document_validation_results_rule_kind'), table_name='document_validation_results')
    op.drop_index(op.f('ix_document_validation_results_outcome'), table_name='document_validation_results')
    op.drop_index(op.f('ix_document_validation_results_document_version_id'), table_name='document_validation_results')
    op.drop_index(op.f('ix_document_validation_results_document_id'), table_name='document_validation_results')
    op.drop_index('ix_di_validation_rule', table_name='document_validation_results')
    op.drop_index('ix_di_validation_outcome', table_name='document_validation_results')
    op.drop_index('ix_di_validation_document', table_name='document_validation_results')
    op.drop_table('document_validation_results')
    op.drop_index(op.f('ix_document_translations_target_language'), table_name='document_translations')
    op.drop_index(op.f('ix_document_translations_document_version_id'), table_name='document_translations')
    op.drop_index(op.f('ix_document_translations_document_id'), table_name='document_translations')
    op.drop_index('ix_di_translation_document', table_name='document_translations')
    op.drop_table('document_translations')
    op.drop_index(op.f('ix_document_summaries_summary_kind'), table_name='document_summaries')
    op.drop_index(op.f('ix_document_summaries_document_version_id'), table_name='document_summaries')
    op.drop_index(op.f('ix_document_summaries_document_id'), table_name='document_summaries')
    op.drop_index('ix_di_summary_document', table_name='document_summaries')
    op.drop_table('document_summaries')
    op.drop_index(op.f('ix_document_reviews_status'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_priority'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_document_version_id'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_document_id'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_assigned_to'), table_name='document_reviews')
    op.drop_index('ix_di_review_status', table_name='document_reviews')
    op.drop_index('ix_di_review_due', table_name='document_reviews')
    op.drop_index('ix_di_review_document', table_name='document_reviews')
    op.drop_index('ix_di_review_assignee', table_name='document_reviews')
    op.drop_table('document_reviews')
    op.drop_index(op.f('ix_document_pages_ocr_quality'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_version_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_index('ix_di_page_quality', table_name='document_pages')
    op.drop_index('ix_di_page_document', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_classifications_is_primary'), table_name='document_classifications')
    op.drop_index(op.f('ix_document_classifications_document_version_id'), table_name='document_classifications')
    op.drop_index(op.f('ix_document_classifications_document_id'), table_name='document_classifications')
    op.drop_index(op.f('ix_document_classifications_category'), table_name='document_classifications')
    op.drop_index('ix_di_classification_document', table_name='document_classifications')
    op.drop_index('ix_di_classification_category', table_name='document_classifications')
    op.drop_table('document_classifications')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_checksum'), table_name='document_versions')
    op.drop_index('ix_di_version_current', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_processing_jobs_status'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_scheduled_at'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_priority'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_document_id'), table_name='document_processing_jobs')
    op.drop_index('ix_di_job_status', table_name='document_processing_jobs')
    op.drop_index('ix_di_job_scheduled', table_name='document_processing_jobs')
    op.drop_index('ix_di_job_priority', table_name='document_processing_jobs')
    op.drop_index('ix_di_job_document', table_name='document_processing_jobs')
    op.drop_table('document_processing_jobs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_requires_review'), table_name='documents')
    op.drop_index(op.f('ix_documents_duplicate_of_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_format'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_archive_parent_id'), table_name='documents')
    op.drop_index('ix_di_document_status', table_name='documents')
    op.drop_index('ix_di_document_format', table_name='documents')
    op.drop_index('ix_di_document_checksum', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_di_statistic_window', table_name='document_statistics')
    op.drop_table('document_statistics')
    op.drop_index(op.f('ix_document_reports_kind'), table_name='document_reports')
    op.drop_index('ix_di_report_kind', table_name='document_reports')
    op.drop_table('document_reports')
    op.drop_index(op.f('ix_document_audit_occurred_at'), table_name='document_audit')
    op.drop_index(op.f('ix_document_audit_actor_id'), table_name='document_audit')
    op.drop_index(op.f('ix_document_audit_action'), table_name='document_audit')
    op.drop_index('ix_di_audit_occurred', table_name='document_audit')
    op.drop_index('ix_di_audit_entity', table_name='document_audit')
    op.drop_index('ix_di_audit_action', table_name='document_audit')
    op.drop_table('document_audit')
    # ### end Alembic commands ###
