"""initial testing quality framework schema

Revision ID: 65a20238475b
Revises: 
Create Date: 2026-08-17 15:32:35.226434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a20238475b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_results',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_results_name'), 'benchmark_results', ['name'], unique=False)
    op.create_table('contract_tests',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_test_type', 'contract_tests', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contract_tests_contract_type'), 'contract_tests', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contract_tests_name'), 'contract_tests', ['name'], unique=False)
    op.create_index(op.f('ix_contract_tests_status'), 'contract_tests', ['status'], unique=False)
    op.create_table('mock_services',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mock_type', sa.String(length=24), nullable=False),
    sa.Column('target_ref', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_mock_service_name')
    )
    op.create_index(op.f('ix_mock_services_mock_type'), 'mock_services', ['mock_type'], unique=False)
    op.create_index(op.f('ix_mock_services_name'), 'mock_services', ['name'], unique=False)
    op.create_table('pipeline_results',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_results_name'), 'pipeline_results', ['name'], unique=False)
    op.create_index(op.f('ix_pipeline_results_status'), 'pipeline_results', ['status'], unique=False)
    op.create_table('qa_audit',
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_audit_action'), 'qa_audit', ['action'], unique=False)
    op.create_index('ix_qa_audit_entity', 'qa_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_qa_audit_entity_id'), 'qa_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_qa_audit_occurred_at'), 'qa_audit', ['occurred_at'], unique=False)
    op.create_table('qa_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_report_kind', 'qa_reports', ['kind'], unique=False)
    op.create_index('ix_qa_report_status', 'qa_reports', ['status'], unique=False)
    op.create_index(op.f('ix_qa_reports_kind'), 'qa_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_qa_reports_status'), 'qa_reports', ['status'], unique=False)
    op.create_table('qa_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_run_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('flaky_count', sa.Integer(), nullable=False),
    sa.Column('quality_gate_failure_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_qa_statistic_window')
    )
    op.create_index(op.f('ix_qa_statistics_window_start'), 'qa_statistics', ['window_start'], unique=False)
    op.create_table('quality_gates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gate_type', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_quality_gate_name')
    )
    op.create_index(op.f('ix_quality_gates_gate_type'), 'quality_gates', ['gate_type'], unique=False)
    op.create_index(op.f('ix_quality_gates_name'), 'quality_gates', ['name'], unique=False)
    op.create_index(op.f('ix_quality_gates_status'), 'quality_gates', ['status'], unique=False)
    op.create_table('synthetic_checks',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_synthetic_check_type', 'synthetic_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_synthetic_checks_check_type'), 'synthetic_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_synthetic_checks_checked_at'), 'synthetic_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_synthetic_checks_name'), 'synthetic_checks', ['name'], unique=False)
    op.create_index(op.f('ix_synthetic_checks_status'), 'synthetic_checks', ['status'], unique=False)
    op.create_table('test_data_sets',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_test_data_set_name')
    )
    op.create_index(op.f('ix_test_data_sets_name'), 'test_data_sets', ['name'], unique=False)
    op.create_table('test_environments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('environment_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_test_environment_name')
    )
    op.create_index(op.f('ix_test_environments_environment_type'), 'test_environments', ['environment_type'], unique=False)
    op.create_index(op.f('ix_test_environments_name'), 'test_environments', ['name'], unique=False)
    op.create_table('test_suites',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('test_type', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_test_suite_name')
    )
    op.create_index(op.f('ix_test_suites_name'), 'test_suites', ['name'], unique=False)
    op.create_index(op.f('ix_test_suites_test_type'), 'test_suites', ['test_type'], unique=False)
    op.create_table('test_cases',
    sa.Column('test_suite_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_case_suite', 'test_cases', ['test_suite_id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_suite_id'), 'test_cases', ['test_suite_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('test_suite_id', sa.Uuid(), nullable=False),
    sa.Column('test_environment_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_environment_id'], ['test_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_run_status', 'test_runs', ['status'], unique=False)
    op.create_index('ix_test_run_suite', 'test_runs', ['test_suite_id'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_test_suite_id'), 'test_runs', ['test_suite_id'], unique=False)
    op.create_table('chaos_results',
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('fault_type', sa.String(length=24), nullable=False),
    sa.Column('recovery_time_seconds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chaos_result_run', 'chaos_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_chaos_results_fault_type'), 'chaos_results', ['fault_type'], unique=False)
    op.create_index(op.f('ix_chaos_results_status'), 'chaos_results', ['status'], unique=False)
    op.create_index(op.f('ix_chaos_results_test_run_id'), 'chaos_results', ['test_run_id'], unique=False)
    op.create_table('coverage_reports',
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('coverage_type', sa.String(length=16), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('lines_covered', sa.Integer(), nullable=False),
    sa.Column('lines_total', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coverage_report_run', 'coverage_reports', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_coverage_reports_coverage_type'), 'coverage_reports', ['coverage_type'], unique=False)
    op.create_index(op.f('ix_coverage_reports_test_run_id'), 'coverage_reports', ['test_run_id'], unique=False)
    op.create_table('performance_results',
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('performance_type', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('throughput_rps', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_result_run', 'performance_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_performance_results_performance_type'), 'performance_results', ['performance_type'], unique=False)
    op.create_index(op.f('ix_performance_results_test_run_id'), 'performance_results', ['test_run_id'], unique=False)
    op.create_table('security_results',
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('security_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_result_run', 'security_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_security_results_security_type'), 'security_results', ['security_type'], unique=False)
    op.create_index(op.f('ix_security_results_status'), 'security_results', ['status'], unique=False)
    op.create_index(op.f('ix_security_results_test_run_id'), 'security_results', ['test_run_id'], unique=False)
    op.create_table('test_results',
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_result_case', 'test_results', ['test_case_id'], unique=False)
    op.create_index('ix_test_result_run', 'test_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index('ix_test_result_run', table_name='test_results')
    op.drop_index('ix_test_result_case', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_security_results_test_run_id'), table_name='security_results')
    op.drop_index(op.f('ix_security_results_status'), table_name='security_results')
    op.drop_index(op.f('ix_security_results_security_type'), table_name='security_results')
    op.drop_index('ix_security_result_run', table_name='security_results')
    op.drop_table('security_results')
    op.drop_index(op.f('ix_performance_results_test_run_id'), table_name='performance_results')
    op.drop_index(op.f('ix_performance_results_performance_type'), table_name='performance_results')
    op.drop_index('ix_performance_result_run', table_name='performance_results')
    op.drop_table('performance_results')
    op.drop_index(op.f('ix_coverage_reports_test_run_id'), table_name='coverage_reports')
    op.drop_index(op.f('ix_coverage_reports_coverage_type'), table_name='coverage_reports')
    op.drop_index('ix_coverage_report_run', table_name='coverage_reports')
    op.drop_table('coverage_reports')
    op.drop_index(op.f('ix_chaos_results_test_run_id'), table_name='chaos_results')
    op.drop_index(op.f('ix_chaos_results_status'), table_name='chaos_results')
    op.drop_index(op.f('ix_chaos_results_fault_type'), table_name='chaos_results')
    op.drop_index('ix_chaos_result_run', table_name='chaos_results')
    op.drop_table('chaos_results')
    op.drop_index(op.f('ix_test_runs_test_suite_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index('ix_test_run_suite', table_name='test_runs')
    op.drop_index('ix_test_run_status', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_cases_test_suite_id'), table_name='test_cases')
    op.drop_index('ix_test_case_suite', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_test_suites_test_type'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_name'), table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_test_environments_name'), table_name='test_environments')
    op.drop_index(op.f('ix_test_environments_environment_type'), table_name='test_environments')
    op.drop_table('test_environments')
    op.drop_index(op.f('ix_test_data_sets_name'), table_name='test_data_sets')
    op.drop_table('test_data_sets')
    op.drop_index(op.f('ix_synthetic_checks_status'), table_name='synthetic_checks')
    op.drop_index(op.f('ix_synthetic_checks_name'), table_name='synthetic_checks')
    op.drop_index(op.f('ix_synthetic_checks_checked_at'), table_name='synthetic_checks')
    op.drop_index(op.f('ix_synthetic_checks_check_type'), table_name='synthetic_checks')
    op.drop_index('ix_synthetic_check_type', table_name='synthetic_checks')
    op.drop_table('synthetic_checks')
    op.drop_index(op.f('ix_quality_gates_status'), table_name='quality_gates')
    op.drop_index(op.f('ix_quality_gates_name'), table_name='quality_gates')
    op.drop_index(op.f('ix_quality_gates_gate_type'), table_name='quality_gates')
    op.drop_table('quality_gates')
    op.drop_index(op.f('ix_qa_statistics_window_start'), table_name='qa_statistics')
    op.drop_table('qa_statistics')
    op.drop_index(op.f('ix_qa_reports_status'), table_name='qa_reports')
    op.drop_index(op.f('ix_qa_reports_kind'), table_name='qa_reports')
    op.drop_index('ix_qa_report_status', table_name='qa_reports')
    op.drop_index('ix_qa_report_kind', table_name='qa_reports')
    op.drop_table('qa_reports')
    op.drop_index(op.f('ix_qa_audit_occurred_at'), table_name='qa_audit')
    op.drop_index(op.f('ix_qa_audit_entity_id'), table_name='qa_audit')
    op.drop_index('ix_qa_audit_entity', table_name='qa_audit')
    op.drop_index(op.f('ix_qa_audit_action'), table_name='qa_audit')
    op.drop_table('qa_audit')
    op.drop_index(op.f('ix_pipeline_results_status'), table_name='pipeline_results')
    op.drop_index(op.f('ix_pipeline_results_name'), table_name='pipeline_results')
    op.drop_table('pipeline_results')
    op.drop_index(op.f('ix_mock_services_name'), table_name='mock_services')
    op.drop_index(op.f('ix_mock_services_mock_type'), table_name='mock_services')
    op.drop_table('mock_services')
    op.drop_index(op.f('ix_contract_tests_status'), table_name='contract_tests')
    op.drop_index(op.f('ix_contract_tests_name'), table_name='contract_tests')
    op.drop_index(op.f('ix_contract_tests_contract_type'), table_name='contract_tests')
    op.drop_index('ix_contract_test_type', table_name='contract_tests')
    op.drop_table('contract_tests')
    op.drop_index(op.f('ix_benchmark_results_name'), table_name='benchmark_results')
    op.drop_table('benchmark_results')
    # ### end Alembic commands ###
