"""initial schema

Revision ID: 2da02d7b1abe
Revises: 
Create Date: 2026-08-14 11:50:30.545723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da02d7b1abe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_audit_action'), 'edge_audit', ['action'], unique=False)
    op.create_index('ix_edge_audit_actor', 'edge_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_edge_audit_actor_id'), 'edge_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_edge_audit_occurred_at'), 'edge_audit', ['occurred_at'], unique=False)
    op.create_index('ix_edge_audit_time', 'edge_audit', ['occurred_at'], unique=False)
    op.create_table('edge_firmware',
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_of_life_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skew_rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_firmware_device_type', 'edge_firmware', ['device_type'], unique=False)
    op.create_table('edge_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_report_kind', 'edge_reports', ['kind'], unique=False)
    op.create_index('ix_edge_report_status', 'edge_reports', ['status'], unique=False)
    op.create_index(op.f('ix_edge_reports_kind'), 'edge_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_edge_reports_status'), 'edge_reports', ['status'], unique=False)
    op.create_table('edge_sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geo_latitude', sa.Float(), nullable=True),
    sa.Column('geo_longitude', sa.Float(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_site_name', 'edge_sites', ['name'], unique=False)
    op.create_index(op.f('ix_edge_sites_name'), 'edge_sites', ['name'], unique=False)
    op.create_table('edge_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sites_registered', sa.Integer(), nullable=False),
    sa.Column('devices_online', sa.Integer(), nullable=False),
    sa.Column('devices_offline', sa.Integer(), nullable=False),
    sa.Column('synchronizations_completed', sa.Integer(), nullable=False),
    sa.Column('synchronizations_failed', sa.Integer(), nullable=False),
    sa.Column('updates_completed', sa.Integer(), nullable=False),
    sa.Column('updates_failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_edge_statistic_window')
    )
    op.create_index('ix_edge_statistic_window', 'edge_statistics', ['window_start'], unique=False)
    op.create_index(op.f('ix_edge_statistics_window_start'), 'edge_statistics', ['window_start'], unique=False)
    op.create_table('edge_clusters',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['edge_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_cluster_site', 'edge_clusters', ['site_id'], unique=False)
    op.create_index(op.f('ix_edge_clusters_site_id'), 'edge_clusters', ['site_id'], unique=False)
    op.create_table('edge_locations',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('parent_location_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hierarchy_level', sa.String(length=24), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_location_id'], ['edge_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['edge_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_location_parent', 'edge_locations', ['parent_location_id'], unique=False)
    op.create_index('ix_edge_location_site', 'edge_locations', ['site_id'], unique=False)
    op.create_index(op.f('ix_edge_locations_hierarchy_level'), 'edge_locations', ['hierarchy_level'], unique=False)
    op.create_index(op.f('ix_edge_locations_parent_location_id'), 'edge_locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('ix_edge_locations_site_id'), 'edge_locations', ['site_id'], unique=False)
    op.create_table('edge_gateways',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=24), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['edge_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['edge_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_gateway_lifecycle_state', 'edge_gateways', ['lifecycle_state'], unique=False)
    op.create_index('ix_edge_gateway_site', 'edge_gateways', ['site_id'], unique=False)
    op.create_index(op.f('ix_edge_gateways_health_status'), 'edge_gateways', ['health_status'], unique=False)
    op.create_index(op.f('ix_edge_gateways_lifecycle_state'), 'edge_gateways', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_edge_gateways_name'), 'edge_gateways', ['name'], unique=False)
    op.create_index(op.f('ix_edge_gateways_site_id'), 'edge_gateways', ['site_id'], unique=False)
    op.create_table('edge_devices',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('gateway_id', sa.Uuid(), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=24), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_schedulable', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['edge_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gateway_id'], ['edge_gateways.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['edge_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['edge_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_device_gateway', 'edge_devices', ['gateway_id'], unique=False)
    op.create_index('ix_edge_device_health_status', 'edge_devices', ['health_status'], unique=False)
    op.create_index('ix_edge_device_lifecycle_state', 'edge_devices', ['lifecycle_state'], unique=False)
    op.create_index('ix_edge_device_site', 'edge_devices', ['site_id'], unique=False)
    op.create_index('ix_edge_device_type', 'edge_devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_edge_devices_device_type'), 'edge_devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_edge_devices_gateway_id'), 'edge_devices', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_edge_devices_health_status'), 'edge_devices', ['health_status'], unique=False)
    op.create_index(op.f('ix_edge_devices_lifecycle_state'), 'edge_devices', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_edge_devices_name'), 'edge_devices', ['name'], unique=False)
    op.create_index(op.f('ix_edge_devices_site_id'), 'edge_devices', ['site_id'], unique=False)
    op.create_table('edge_ai_models',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('rollback_of_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inference_target', sa.String(length=8), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['edge_ai_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_ai_model_device', 'edge_ai_models', ['device_id'], unique=False)
    op.create_index('ix_edge_ai_model_status', 'edge_ai_models', ['status'], unique=False)
    op.create_index(op.f('ix_edge_ai_models_device_id'), 'edge_ai_models', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_ai_models_status'), 'edge_ai_models', ['status'], unique=False)
    op.create_table('edge_applications',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('deployment_strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_application_device', 'edge_applications', ['device_id'], unique=False)
    op.create_index('ix_edge_application_status', 'edge_applications', ['status'], unique=False)
    op.create_index(op.f('ix_edge_applications_device_id'), 'edge_applications', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_applications_status'), 'edge_applications', ['status'], unique=False)
    op.create_table('edge_configurations',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_configuration_device', 'edge_configurations', ['device_id'], unique=False)
    op.create_index('ix_edge_configuration_key', 'edge_configurations', ['config_key'], unique=False)
    op.create_index(op.f('ix_edge_configurations_config_key'), 'edge_configurations', ['config_key'], unique=False)
    op.create_index(op.f('ix_edge_configurations_device_id'), 'edge_configurations', ['device_id'], unique=False)
    op.create_table('edge_health',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('component', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_health_checked_at', 'edge_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_edge_health_component'), 'edge_health', ['component'], unique=False)
    op.create_index('ix_edge_health_device', 'edge_health', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_health_device_id'), 'edge_health', ['device_id'], unique=False)
    op.create_table('edge_inventory',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('resource_kind', sa.String(length=64), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_inventory_collected_at'), 'edge_inventory', ['collected_at'], unique=False)
    op.create_index('ix_edge_inventory_device', 'edge_inventory', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_inventory_device_id'), 'edge_inventory', ['device_id'], unique=False)
    op.create_index('ix_edge_inventory_kind', 'edge_inventory', ['resource_kind'], unique=False)
    op.create_index(op.f('ix_edge_inventory_resource_kind'), 'edge_inventory', ['resource_kind'], unique=False)
    op.create_table('edge_protocols',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_protocol_device', 'edge_protocols', ['device_id'], unique=False)
    op.create_index('ix_edge_protocol_kind', 'edge_protocols', ['protocol_kind'], unique=False)
    op.create_index(op.f('ix_edge_protocols_device_id'), 'edge_protocols', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_protocols_protocol_kind'), 'edge_protocols', ['protocol_kind'], unique=False)
    op.create_table('edge_synchronization',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('sync_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_sync_device', 'edge_synchronization', ['device_id'], unique=False)
    op.create_index('ix_edge_sync_status', 'edge_synchronization', ['status'], unique=False)
    op.create_index(op.f('ix_edge_synchronization_device_id'), 'edge_synchronization', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_synchronization_status'), 'edge_synchronization', ['status'], unique=False)
    op.create_table('edge_updates',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('update_kind', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_update_device', 'edge_updates', ['device_id'], unique=False)
    op.create_index('ix_edge_update_status', 'edge_updates', ['status'], unique=False)
    op.create_index(op.f('ix_edge_updates_device_id'), 'edge_updates', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_updates_status'), 'edge_updates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_updates_status'), table_name='edge_updates')
    op.drop_index(op.f('ix_edge_updates_device_id'), table_name='edge_updates')
    op.drop_index('ix_edge_update_status', table_name='edge_updates')
    op.drop_index('ix_edge_update_device', table_name='edge_updates')
    op.drop_table('edge_updates')
    op.drop_index(op.f('ix_edge_synchronization_status'), table_name='edge_synchronization')
    op.drop_index(op.f('ix_edge_synchronization_device_id'), table_name='edge_synchronization')
    op.drop_index('ix_edge_sync_status', table_name='edge_synchronization')
    op.drop_index('ix_edge_sync_device', table_name='edge_synchronization')
    op.drop_table('edge_synchronization')
    op.drop_index(op.f('ix_edge_protocols_protocol_kind'), table_name='edge_protocols')
    op.drop_index(op.f('ix_edge_protocols_device_id'), table_name='edge_protocols')
    op.drop_index('ix_edge_protocol_kind', table_name='edge_protocols')
    op.drop_index('ix_edge_protocol_device', table_name='edge_protocols')
    op.drop_table('edge_protocols')
    op.drop_index(op.f('ix_edge_inventory_resource_kind'), table_name='edge_inventory')
    op.drop_index('ix_edge_inventory_kind', table_name='edge_inventory')
    op.drop_index(op.f('ix_edge_inventory_device_id'), table_name='edge_inventory')
    op.drop_index('ix_edge_inventory_device', table_name='edge_inventory')
    op.drop_index(op.f('ix_edge_inventory_collected_at'), table_name='edge_inventory')
    op.drop_table('edge_inventory')
    op.drop_index(op.f('ix_edge_health_device_id'), table_name='edge_health')
    op.drop_index('ix_edge_health_device', table_name='edge_health')
    op.drop_index(op.f('ix_edge_health_component'), table_name='edge_health')
    op.drop_index('ix_edge_health_checked_at', table_name='edge_health')
    op.drop_table('edge_health')
    op.drop_index(op.f('ix_edge_configurations_device_id'), table_name='edge_configurations')
    op.drop_index(op.f('ix_edge_configurations_config_key'), table_name='edge_configurations')
    op.drop_index('ix_edge_configuration_key', table_name='edge_configurations')
    op.drop_index('ix_edge_configuration_device', table_name='edge_configurations')
    op.drop_table('edge_configurations')
    op.drop_index(op.f('ix_edge_applications_status'), table_name='edge_applications')
    op.drop_index(op.f('ix_edge_applications_device_id'), table_name='edge_applications')
    op.drop_index('ix_edge_application_status', table_name='edge_applications')
    op.drop_index('ix_edge_application_device', table_name='edge_applications')
    op.drop_table('edge_applications')
    op.drop_index(op.f('ix_edge_ai_models_status'), table_name='edge_ai_models')
    op.drop_index(op.f('ix_edge_ai_models_device_id'), table_name='edge_ai_models')
    op.drop_index('ix_edge_ai_model_status', table_name='edge_ai_models')
    op.drop_index('ix_edge_ai_model_device', table_name='edge_ai_models')
    op.drop_table('edge_ai_models')
    op.drop_index(op.f('ix_edge_devices_site_id'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_name'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_lifecycle_state'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_health_status'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_gateway_id'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_device_type'), table_name='edge_devices')
    op.drop_index('ix_edge_device_type', table_name='edge_devices')
    op.drop_index('ix_edge_device_site', table_name='edge_devices')
    op.drop_index('ix_edge_device_lifecycle_state', table_name='edge_devices')
    op.drop_index('ix_edge_device_health_status', table_name='edge_devices')
    op.drop_index('ix_edge_device_gateway', table_name='edge_devices')
    op.drop_table('edge_devices')
    op.drop_index(op.f('ix_edge_gateways_site_id'), table_name='edge_gateways')
    op.drop_index(op.f('ix_edge_gateways_name'), table_name='edge_gateways')
    op.drop_index(op.f('ix_edge_gateways_lifecycle_state'), table_name='edge_gateways')
    op.drop_index(op.f('ix_edge_gateways_health_status'), table_name='edge_gateways')
    op.drop_index('ix_edge_gateway_site', table_name='edge_gateways')
    op.drop_index('ix_edge_gateway_lifecycle_state', table_name='edge_gateways')
    op.drop_table('edge_gateways')
    op.drop_index(op.f('ix_edge_locations_site_id'), table_name='edge_locations')
    op.drop_index(op.f('ix_edge_locations_parent_location_id'), table_name='edge_locations')
    op.drop_index(op.f('ix_edge_locations_hierarchy_level'), table_name='edge_locations')
    op.drop_index('ix_edge_location_site', table_name='edge_locations')
    op.drop_index('ix_edge_location_parent', table_name='edge_locations')
    op.drop_table('edge_locations')
    op.drop_index(op.f('ix_edge_clusters_site_id'), table_name='edge_clusters')
    op.drop_index('ix_edge_cluster_site', table_name='edge_clusters')
    op.drop_table('edge_clusters')
    op.drop_index(op.f('ix_edge_statistics_window_start'), table_name='edge_statistics')
    op.drop_index('ix_edge_statistic_window', table_name='edge_statistics')
    op.drop_table('edge_statistics')
    op.drop_index(op.f('ix_edge_sites_name'), table_name='edge_sites')
    op.drop_index('ix_edge_site_name', table_name='edge_sites')
    op.drop_table('edge_sites')
    op.drop_index(op.f('ix_edge_reports_status'), table_name='edge_reports')
    op.drop_index(op.f('ix_edge_reports_kind'), table_name='edge_reports')
    op.drop_index('ix_edge_report_status', table_name='edge_reports')
    op.drop_index('ix_edge_report_kind', table_name='edge_reports')
    op.drop_table('edge_reports')
    op.drop_index('ix_edge_firmware_device_type', table_name='edge_firmware')
    op.drop_table('edge_firmware')
    op.drop_index('ix_edge_audit_time', table_name='edge_audit')
    op.drop_index(op.f('ix_edge_audit_occurred_at'), table_name='edge_audit')
    op.drop_index(op.f('ix_edge_audit_actor_id'), table_name='edge_audit')
    op.drop_index('ix_edge_audit_actor', table_name='edge_audit')
    op.drop_index(op.f('ix_edge_audit_action'), table_name='edge_audit')
    op.drop_table('edge_audit')
    # ### end Alembic commands ###
