"""initial schema

Revision ID: 0d036b64a14d
Revises: 
Create Date: 2026-08-14 16:19:54.883132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d036b64a14d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_audit_action', 'cloud_audit', ['action'], unique=False)
    op.create_index('ix_cloud_audit_actor', 'cloud_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_cloud_audit_actor_id'), 'cloud_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_cloud_audit_occurred_at'), 'cloud_audit', ['occurred_at'], unique=False)
    op.create_index('ix_cloud_audit_time', 'cloud_audit', ['occurred_at'], unique=False)
    op.create_table('cloud_catalog',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_catalog_resource_type'), 'cloud_catalog', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cloud_catalog_status'), 'cloud_catalog', ['status'], unique=False)
    op.create_table('cloud_providers',
    sa.Column('provider_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_provider_type', 'cloud_providers', ['provider_type'], unique=False)
    op.create_index(op.f('ix_cloud_providers_provider_type'), 'cloud_providers', ['provider_type'], unique=False)
    op.create_table('cloud_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_report_kind', 'cloud_reports', ['kind'], unique=False)
    op.create_index('ix_cloud_report_status', 'cloud_reports', ['status'], unique=False)
    op.create_index(op.f('ix_cloud_reports_kind'), 'cloud_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_cloud_reports_status'), 'cloud_reports', ['status'], unique=False)
    op.create_table('cloud_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resources_discovered', sa.Integer(), nullable=False),
    sa.Column('resources_provisioned', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('budgets_exceeded', sa.Integer(), nullable=False),
    sa.Column('drift_detected_count', sa.Integer(), nullable=False),
    sa.Column('compliance_violations', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_cloud_statistic_window')
    )
    op.create_index('ix_cloud_statistic_window', 'cloud_statistics', ['window_start'], unique=False)
    op.create_index(op.f('ix_cloud_statistics_window_start'), 'cloud_statistics', ['window_start'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_ref', sa.String(length=512), nullable=False),
    sa.Column('credential_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_account_health_status', 'cloud_accounts', ['health_status'], unique=False)
    op.create_index('ix_cloud_account_provider', 'cloud_accounts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_external_account_id'), 'cloud_accounts', ['external_account_id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_health_status'), 'cloud_accounts', ['health_status'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_name'), 'cloud_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_provider_id'), 'cloud_accounts', ['provider_id'], unique=False)
    op.create_table('cloud_regions',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_region_provider', 'cloud_regions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_cloud_regions_code'), 'cloud_regions', ['code'], unique=False)
    op.create_index(op.f('ix_cloud_regions_provider_id'), 'cloud_regions', ['provider_id'], unique=False)
    op.create_table('cloud_budgets',
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('threshold_fraction', sa.Float(), nullable=False),
    sa.Column('current_spend', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_budget_account', 'cloud_budgets', ['account_id'], unique=False)
    op.create_table('cloud_compliance',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remediation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_compliance_account', 'cloud_compliance', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_compliance_account_id'), 'cloud_compliance', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_compliance_framework'), 'cloud_compliance', ['framework'], unique=False)
    op.create_table('cloud_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scope_account_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scope_account_id'], ['cloud_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_policies_policy_type'), 'cloud_policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_cloud_policies_status'), 'cloud_policies', ['status'], unique=False)
    op.create_index('ix_cloud_policy_status', 'cloud_policies', ['status'], unique=False)
    op.create_index('ix_cloud_policy_type', 'cloud_policies', ['policy_type'], unique=False)
    op.create_table('cloud_projects',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('external_project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_project_account', 'cloud_projects', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_projects_account_id'), 'cloud_projects', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_projects_external_project_id'), 'cloud_projects', ['external_project_id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('cloud_project_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cloud_project_id'], ['cloud_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['cloud_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_resource_account', 'cloud_resources', ['account_id'], unique=False)
    op.create_index('ix_cloud_resource_lifecycle_state', 'cloud_resources', ['lifecycle_state'], unique=False)
    op.create_index('ix_cloud_resource_project', 'cloud_resources', ['cloud_project_id'], unique=False)
    op.create_index('ix_cloud_resource_region', 'cloud_resources', ['region_id'], unique=False)
    op.create_index('ix_cloud_resource_type', 'cloud_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cloud_resources_account_id'), 'cloud_resources', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_external_id'), 'cloud_resources', ['external_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_lifecycle_state'), 'cloud_resources', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_cloud_resources_name'), 'cloud_resources', ['name'], unique=False)
    op.create_index(op.f('ix_cloud_resources_resource_type'), 'cloud_resources', ['resource_type'], unique=False)
    op.create_table('cloud_compute',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('instance_type', sa.String(length=64), nullable=True),
    sa.Column('vcpu', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Float(), nullable=True),
    sa.Column('is_spot', sa.Boolean(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('is_gpu', sa.Boolean(), nullable=False),
    sa.Column('image_ref', sa.String(length=512), nullable=True),
    sa.Column('utilization_fraction', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_compute_resource', 'cloud_compute', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_compute_resource_id'), 'cloud_compute', ['resource_id'], unique=False)
    op.create_table('cloud_costs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('cost_category', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_cost_account', 'cloud_costs', ['account_id'], unique=False)
    op.create_index('ix_cloud_cost_period', 'cloud_costs', ['period_start'], unique=False)
    op.create_index('ix_cloud_cost_resource', 'cloud_costs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_costs_account_id'), 'cloud_costs', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_costs_cost_category'), 'cloud_costs', ['cost_category'], unique=False)
    op.create_index(op.f('ix_cloud_costs_period_start'), 'cloud_costs', ['period_start'], unique=False)
    op.create_table('cloud_databases',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('is_high_availability', sa.Boolean(), nullable=False),
    sa.Column('storage_gb', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_database_resource', 'cloud_databases', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_databases_resource_id'), 'cloud_databases', ['resource_id'], unique=False)
    op.create_table('cloud_drift',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('desired_state_hash', sa.String(length=128), nullable=True),
    sa.Column('live_state_hash', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_drift_detected_at'), 'cloud_drift', ['detected_at'], unique=False)
    op.create_index('ix_cloud_drift_resource', 'cloud_drift', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_drift_resource_id'), 'cloud_drift', ['resource_id'], unique=False)
    op.create_index('ix_cloud_drift_status', 'cloud_drift', ['status'], unique=False)
    op.create_table('cloud_iac',
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('tool', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('state_reference', sa.String(length=512), nullable=True),
    sa.Column('version_label', sa.String(length=32), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_iac_resource', 'cloud_iac', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_iac_status'), 'cloud_iac', ['status'], unique=False)
    op.create_table('cloud_kubernetes',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_reference_id', sa.Uuid(), nullable=True),
    sa.Column('node_pool_count', sa.Integer(), nullable=False),
    sa.Column('kubernetes_version', sa.String(length=32), nullable=True),
    sa.Column('autoscaling_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_kubernetes_resource', 'cloud_kubernetes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_kubernetes_resource_id'), 'cloud_kubernetes', ['resource_id'], unique=False)
    op.create_table('cloud_networks',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('cidr_block', sa.String(length=64), nullable=True),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_network_resource', 'cloud_networks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_networks_resource_id'), 'cloud_networks', ['resource_id'], unique=False)
    op.create_table('cloud_storage',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('storage_class', sa.String(length=64), nullable=True),
    sa.Column('capacity_gb', sa.Float(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_replicated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_storage_resource', 'cloud_storage', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_storage_resource_id'), 'cloud_storage', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_storage_resource_id'), table_name='cloud_storage')
    op.drop_index('ix_cloud_storage_resource', table_name='cloud_storage')
    op.drop_table('cloud_storage')
    op.drop_index(op.f('ix_cloud_networks_resource_id'), table_name='cloud_networks')
    op.drop_index('ix_cloud_network_resource', table_name='cloud_networks')
    op.drop_table('cloud_networks')
    op.drop_index(op.f('ix_cloud_kubernetes_resource_id'), table_name='cloud_kubernetes')
    op.drop_index('ix_cloud_kubernetes_resource', table_name='cloud_kubernetes')
    op.drop_table('cloud_kubernetes')
    op.drop_index(op.f('ix_cloud_iac_status'), table_name='cloud_iac')
    op.drop_index('ix_cloud_iac_resource', table_name='cloud_iac')
    op.drop_table('cloud_iac')
    op.drop_index('ix_cloud_drift_status', table_name='cloud_drift')
    op.drop_index(op.f('ix_cloud_drift_resource_id'), table_name='cloud_drift')
    op.drop_index('ix_cloud_drift_resource', table_name='cloud_drift')
    op.drop_index(op.f('ix_cloud_drift_detected_at'), table_name='cloud_drift')
    op.drop_table('cloud_drift')
    op.drop_index(op.f('ix_cloud_databases_resource_id'), table_name='cloud_databases')
    op.drop_index('ix_cloud_database_resource', table_name='cloud_databases')
    op.drop_table('cloud_databases')
    op.drop_index(op.f('ix_cloud_costs_period_start'), table_name='cloud_costs')
    op.drop_index(op.f('ix_cloud_costs_cost_category'), table_name='cloud_costs')
    op.drop_index(op.f('ix_cloud_costs_account_id'), table_name='cloud_costs')
    op.drop_index('ix_cloud_cost_resource', table_name='cloud_costs')
    op.drop_index('ix_cloud_cost_period', table_name='cloud_costs')
    op.drop_index('ix_cloud_cost_account', table_name='cloud_costs')
    op.drop_table('cloud_costs')
    op.drop_index(op.f('ix_cloud_compute_resource_id'), table_name='cloud_compute')
    op.drop_index('ix_cloud_compute_resource', table_name='cloud_compute')
    op.drop_table('cloud_compute')
    op.drop_index(op.f('ix_cloud_resources_resource_type'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_name'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_lifecycle_state'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_external_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_account_id'), table_name='cloud_resources')
    op.drop_index('ix_cloud_resource_type', table_name='cloud_resources')
    op.drop_index('ix_cloud_resource_region', table_name='cloud_resources')
    op.drop_index('ix_cloud_resource_project', table_name='cloud_resources')
    op.drop_index('ix_cloud_resource_lifecycle_state', table_name='cloud_resources')
    op.drop_index('ix_cloud_resource_account', table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_cloud_projects_external_project_id'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_account_id'), table_name='cloud_projects')
    op.drop_index('ix_cloud_project_account', table_name='cloud_projects')
    op.drop_table('cloud_projects')
    op.drop_index('ix_cloud_policy_type', table_name='cloud_policies')
    op.drop_index('ix_cloud_policy_status', table_name='cloud_policies')
    op.drop_index(op.f('ix_cloud_policies_status'), table_name='cloud_policies')
    op.drop_index(op.f('ix_cloud_policies_policy_type'), table_name='cloud_policies')
    op.drop_table('cloud_policies')
    op.drop_index(op.f('ix_cloud_compliance_framework'), table_name='cloud_compliance')
    op.drop_index(op.f('ix_cloud_compliance_account_id'), table_name='cloud_compliance')
    op.drop_index('ix_cloud_compliance_account', table_name='cloud_compliance')
    op.drop_table('cloud_compliance')
    op.drop_index('ix_cloud_budget_account', table_name='cloud_budgets')
    op.drop_table('cloud_budgets')
    op.drop_index(op.f('ix_cloud_regions_provider_id'), table_name='cloud_regions')
    op.drop_index(op.f('ix_cloud_regions_code'), table_name='cloud_regions')
    op.drop_index('ix_cloud_region_provider', table_name='cloud_regions')
    op.drop_table('cloud_regions')
    op.drop_index(op.f('ix_cloud_accounts_provider_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_name'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_health_status'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_external_account_id'), table_name='cloud_accounts')
    op.drop_index('ix_cloud_account_provider', table_name='cloud_accounts')
    op.drop_index('ix_cloud_account_health_status', table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_cloud_statistics_window_start'), table_name='cloud_statistics')
    op.drop_index('ix_cloud_statistic_window', table_name='cloud_statistics')
    op.drop_table('cloud_statistics')
    op.drop_index(op.f('ix_cloud_reports_status'), table_name='cloud_reports')
    op.drop_index(op.f('ix_cloud_reports_kind'), table_name='cloud_reports')
    op.drop_index('ix_cloud_report_status', table_name='cloud_reports')
    op.drop_index('ix_cloud_report_kind', table_name='cloud_reports')
    op.drop_table('cloud_reports')
    op.drop_index(op.f('ix_cloud_providers_provider_type'), table_name='cloud_providers')
    op.drop_index('ix_cloud_provider_type', table_name='cloud_providers')
    op.drop_table('cloud_providers')
    op.drop_index(op.f('ix_cloud_catalog_status'), table_name='cloud_catalog')
    op.drop_index(op.f('ix_cloud_catalog_resource_type'), table_name='cloud_catalog')
    op.drop_table('cloud_catalog')
    op.drop_index('ix_cloud_audit_time', table_name='cloud_audit')
    op.drop_index(op.f('ix_cloud_audit_occurred_at'), table_name='cloud_audit')
    op.drop_index(op.f('ix_cloud_audit_actor_id'), table_name='cloud_audit')
    op.drop_index('ix_cloud_audit_actor', table_name='cloud_audit')
    op.drop_index('ix_cloud_audit_action', table_name='cloud_audit')
    op.drop_table('cloud_audit')
    # ### end Alembic commands ###
