"""initial schema

Revision ID: 23d969dd9fcb
Revises: 
Create Date: 2026-08-14 10:27:14.763296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d969dd9fcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_audit_action', 'cluster_audit', ['action'], unique=False)
    op.create_index('ix_cluster_audit_actor', 'cluster_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_cluster_audit_actor_id'), 'cluster_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_cluster_audit_occurred_at'), 'cluster_audit', ['occurred_at'], unique=False)
    op.create_index('ix_cluster_audit_time', 'cluster_audit', ['occurred_at'], unique=False)
    op.create_table('cluster_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_group_name', 'cluster_groups', ['name'], unique=False)
    op.create_index(op.f('ix_cluster_groups_name'), 'cluster_groups', ['name'], unique=False)
    op.create_table('cluster_regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('availability_zones', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_region_code', 'cluster_regions', ['code'], unique=False)
    op.create_index(op.f('ix_cluster_regions_code'), 'cluster_regions', ['code'], unique=False)
    op.create_index(op.f('ix_cluster_regions_name'), 'cluster_regions', ['name'], unique=False)
    op.create_table('cluster_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_report_kind', 'cluster_reports', ['kind'], unique=False)
    op.create_index('ix_cluster_report_status', 'cluster_reports', ['status'], unique=False)
    op.create_index(op.f('ix_cluster_reports_kind'), 'cluster_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_cluster_reports_status'), 'cluster_reports', ['status'], unique=False)
    op.create_table('cluster_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clusters_registered', sa.Integer(), nullable=False),
    sa.Column('clusters_healthy', sa.Integer(), nullable=False),
    sa.Column('clusters_degraded', sa.Integer(), nullable=False),
    sa.Column('clusters_unhealthy', sa.Integer(), nullable=False),
    sa.Column('policy_violations', sa.Integer(), nullable=False),
    sa.Column('compliance_violations', sa.Integer(), nullable=False),
    sa.Column('upgrades_completed', sa.Integer(), nullable=False),
    sa.Column('upgrades_failed', sa.Integer(), nullable=False),
    sa.Column('total_node_count', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_cluster_statistic_window')
    )
    op.create_index('ix_cluster_statistic_window', 'cluster_statistics', ['window_start'], unique=False)
    op.create_index(op.f('ix_cluster_statistics_window_start'), 'cluster_statistics', ['window_start'], unique=False)
    op.create_table('cluster_versions',
    sa.Column('cluster_type', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_of_life_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skew_rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_version_type', 'cluster_versions', ['cluster_type'], unique=False)
    op.create_index(op.f('ix_cluster_versions_cluster_type'), 'cluster_versions', ['cluster_type'], unique=False)
    op.create_table('clusters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cluster_type', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=24), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=512), nullable=True),
    sa.Column('kubernetes_version', sa.String(length=32), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_schedulable', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['cluster_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['cluster_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_group', 'clusters', ['group_id'], unique=False)
    op.create_index('ix_cluster_health_status', 'clusters', ['health_status'], unique=False)
    op.create_index('ix_cluster_lifecycle_state', 'clusters', ['lifecycle_state'], unique=False)
    op.create_index('ix_cluster_region', 'clusters', ['region_id'], unique=False)
    op.create_index('ix_cluster_type', 'clusters', ['cluster_type'], unique=False)
    op.create_index(op.f('ix_clusters_cluster_type'), 'clusters', ['cluster_type'], unique=False)
    op.create_index(op.f('ix_clusters_group_id'), 'clusters', ['group_id'], unique=False)
    op.create_index(op.f('ix_clusters_health_status'), 'clusters', ['health_status'], unique=False)
    op.create_index(op.f('ix_clusters_lifecycle_state'), 'clusters', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=False)
    op.create_index(op.f('ix_clusters_region_id'), 'clusters', ['region_id'], unique=False)
    op.create_table('cluster_capacity',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('resource_kind', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_capacity_cluster', 'cluster_capacity', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_capacity_cluster_id'), 'cluster_capacity', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_capacity_kind', 'cluster_capacity', ['resource_kind'], unique=False)
    op.create_index(op.f('ix_cluster_capacity_measured_at'), 'cluster_capacity', ['measured_at'], unique=False)
    op.create_index(op.f('ix_cluster_capacity_resource_kind'), 'cluster_capacity', ['resource_kind'], unique=False)
    op.create_table('cluster_compliance',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remediation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_compliance_cluster', 'cluster_compliance', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_compliance_cluster_id'), 'cluster_compliance', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_compliance_framework', 'cluster_compliance', ['framework'], unique=False)
    op.create_index(op.f('ix_cluster_compliance_status'), 'cluster_compliance', ['status'], unique=False)
    op.create_table('cluster_credentials',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('credential_ref', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_credential_cluster', 'cluster_credentials', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_credentials_cluster_id'), 'cluster_credentials', ['cluster_id'], unique=False)
    op.create_table('cluster_events',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('event_kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_event_cluster', 'cluster_events', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_event_kind', 'cluster_events', ['event_kind'], unique=False)
    op.create_index('ix_cluster_event_occurred', 'cluster_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_cluster_events_cluster_id'), 'cluster_events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_events_event_kind'), 'cluster_events', ['event_kind'], unique=False)
    op.create_index(op.f('ix_cluster_events_occurred_at'), 'cluster_events', ['occurred_at'], unique=False)
    op.create_table('cluster_health',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('component', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_health_checked_at', 'cluster_health', ['checked_at'], unique=False)
    op.create_index('ix_cluster_health_cluster', 'cluster_health', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_health_cluster_id'), 'cluster_health', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_health_component'), 'cluster_health', ['component'], unique=False)
    op.create_table('cluster_inventory',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('resource_kind', sa.String(length=64), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_inventory_cluster', 'cluster_inventory', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_inventory_cluster_id'), 'cluster_inventory', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_inventory_collected_at'), 'cluster_inventory', ['collected_at'], unique=False)
    op.create_index('ix_cluster_inventory_kind', 'cluster_inventory', ['resource_kind'], unique=False)
    op.create_index(op.f('ix_cluster_inventory_resource_kind'), 'cluster_inventory', ['resource_kind'], unique=False)
    op.create_table('cluster_policies',
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('propagation_status', sa.String(length=16), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['cluster_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_policies_cluster_id'), 'cluster_policies', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_policies_group_id'), 'cluster_policies', ['group_id'], unique=False)
    op.create_index(op.f('ix_cluster_policies_policy_type'), 'cluster_policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_cluster_policies_propagation_status'), 'cluster_policies', ['propagation_status'], unique=False)
    op.create_index('ix_cluster_policy_cluster', 'cluster_policies', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_policy_group', 'cluster_policies', ['group_id'], unique=False)
    op.create_index('ix_cluster_policy_status', 'cluster_policies', ['propagation_status'], unique=False)
    op.create_index('ix_cluster_policy_type', 'cluster_policies', ['policy_type'], unique=False)
    op.create_table('cluster_upgrades',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('pre_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('post_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_upgrade_cluster', 'cluster_upgrades', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_upgrade_status', 'cluster_upgrades', ['status'], unique=False)
    op.create_index(op.f('ix_cluster_upgrades_cluster_id'), 'cluster_upgrades', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_upgrades_status'), 'cluster_upgrades', ['status'], unique=False)
    op.create_table('cluster_workloads',
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('deployment_strategy', sa.String(length=16), nullable=False),
    sa.Column('placement_status', sa.String(length=16), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=True),
    sa.Column('affinity_rules', sa.JSON(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_workload_cluster', 'cluster_workloads', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_workload_status', 'cluster_workloads', ['placement_status'], unique=False)
    op.create_index(op.f('ix_cluster_workloads_cluster_id'), 'cluster_workloads', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_workloads_placement_status'), 'cluster_workloads', ['placement_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_workloads_placement_status'), table_name='cluster_workloads')
    op.drop_index(op.f('ix_cluster_workloads_cluster_id'), table_name='cluster_workloads')
    op.drop_index('ix_cluster_workload_status', table_name='cluster_workloads')
    op.drop_index('ix_cluster_workload_cluster', table_name='cluster_workloads')
    op.drop_table('cluster_workloads')
    op.drop_index(op.f('ix_cluster_upgrades_status'), table_name='cluster_upgrades')
    op.drop_index(op.f('ix_cluster_upgrades_cluster_id'), table_name='cluster_upgrades')
    op.drop_index('ix_cluster_upgrade_status', table_name='cluster_upgrades')
    op.drop_index('ix_cluster_upgrade_cluster', table_name='cluster_upgrades')
    op.drop_table('cluster_upgrades')
    op.drop_index('ix_cluster_policy_type', table_name='cluster_policies')
    op.drop_index('ix_cluster_policy_status', table_name='cluster_policies')
    op.drop_index('ix_cluster_policy_group', table_name='cluster_policies')
    op.drop_index('ix_cluster_policy_cluster', table_name='cluster_policies')
    op.drop_index(op.f('ix_cluster_policies_propagation_status'), table_name='cluster_policies')
    op.drop_index(op.f('ix_cluster_policies_policy_type'), table_name='cluster_policies')
    op.drop_index(op.f('ix_cluster_policies_group_id'), table_name='cluster_policies')
    op.drop_index(op.f('ix_cluster_policies_cluster_id'), table_name='cluster_policies')
    op.drop_table('cluster_policies')
    op.drop_index(op.f('ix_cluster_inventory_resource_kind'), table_name='cluster_inventory')
    op.drop_index('ix_cluster_inventory_kind', table_name='cluster_inventory')
    op.drop_index(op.f('ix_cluster_inventory_collected_at'), table_name='cluster_inventory')
    op.drop_index(op.f('ix_cluster_inventory_cluster_id'), table_name='cluster_inventory')
    op.drop_index('ix_cluster_inventory_cluster', table_name='cluster_inventory')
    op.drop_table('cluster_inventory')
    op.drop_index(op.f('ix_cluster_health_component'), table_name='cluster_health')
    op.drop_index(op.f('ix_cluster_health_cluster_id'), table_name='cluster_health')
    op.drop_index('ix_cluster_health_cluster', table_name='cluster_health')
    op.drop_index('ix_cluster_health_checked_at', table_name='cluster_health')
    op.drop_table('cluster_health')
    op.drop_index(op.f('ix_cluster_events_occurred_at'), table_name='cluster_events')
    op.drop_index(op.f('ix_cluster_events_event_kind'), table_name='cluster_events')
    op.drop_index(op.f('ix_cluster_events_cluster_id'), table_name='cluster_events')
    op.drop_index('ix_cluster_event_occurred', table_name='cluster_events')
    op.drop_index('ix_cluster_event_kind', table_name='cluster_events')
    op.drop_index('ix_cluster_event_cluster', table_name='cluster_events')
    op.drop_table('cluster_events')
    op.drop_index(op.f('ix_cluster_credentials_cluster_id'), table_name='cluster_credentials')
    op.drop_index('ix_cluster_credential_cluster', table_name='cluster_credentials')
    op.drop_table('cluster_credentials')
    op.drop_index(op.f('ix_cluster_compliance_status'), table_name='cluster_compliance')
    op.drop_index('ix_cluster_compliance_framework', table_name='cluster_compliance')
    op.drop_index(op.f('ix_cluster_compliance_cluster_id'), table_name='cluster_compliance')
    op.drop_index('ix_cluster_compliance_cluster', table_name='cluster_compliance')
    op.drop_table('cluster_compliance')
    op.drop_index(op.f('ix_cluster_capacity_resource_kind'), table_name='cluster_capacity')
    op.drop_index(op.f('ix_cluster_capacity_measured_at'), table_name='cluster_capacity')
    op.drop_index('ix_cluster_capacity_kind', table_name='cluster_capacity')
    op.drop_index(op.f('ix_cluster_capacity_cluster_id'), table_name='cluster_capacity')
    op.drop_index('ix_cluster_capacity_cluster', table_name='cluster_capacity')
    op.drop_table('cluster_capacity')
    op.drop_index(op.f('ix_clusters_region_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_lifecycle_state'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_health_status'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_group_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_cluster_type'), table_name='clusters')
    op.drop_index('ix_cluster_type', table_name='clusters')
    op.drop_index('ix_cluster_region', table_name='clusters')
    op.drop_index('ix_cluster_lifecycle_state', table_name='clusters')
    op.drop_index('ix_cluster_health_status', table_name='clusters')
    op.drop_index('ix_cluster_group', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_cluster_versions_cluster_type'), table_name='cluster_versions')
    op.drop_index('ix_cluster_version_type', table_name='cluster_versions')
    op.drop_table('cluster_versions')
    op.drop_index(op.f('ix_cluster_statistics_window_start'), table_name='cluster_statistics')
    op.drop_index('ix_cluster_statistic_window', table_name='cluster_statistics')
    op.drop_table('cluster_statistics')
    op.drop_index(op.f('ix_cluster_reports_status'), table_name='cluster_reports')
    op.drop_index(op.f('ix_cluster_reports_kind'), table_name='cluster_reports')
    op.drop_index('ix_cluster_report_status', table_name='cluster_reports')
    op.drop_index('ix_cluster_report_kind', table_name='cluster_reports')
    op.drop_table('cluster_reports')
    op.drop_index(op.f('ix_cluster_regions_name'), table_name='cluster_regions')
    op.drop_index(op.f('ix_cluster_regions_code'), table_name='cluster_regions')
    op.drop_index('ix_cluster_region_code', table_name='cluster_regions')
    op.drop_table('cluster_regions')
    op.drop_index(op.f('ix_cluster_groups_name'), table_name='cluster_groups')
    op.drop_index('ix_cluster_group_name', table_name='cluster_groups')
    op.drop_table('cluster_groups')
    op.drop_index('ix_cluster_audit_time', table_name='cluster_audit')
    op.drop_index(op.f('ix_cluster_audit_occurred_at'), table_name='cluster_audit')
    op.drop_index(op.f('ix_cluster_audit_actor_id'), table_name='cluster_audit')
    op.drop_index('ix_cluster_audit_actor', table_name='cluster_audit')
    op.drop_index('ix_cluster_audit_action', table_name='cluster_audit')
    op.drop_table('cluster_audit')
    # ### end Alembic commands ###
