"""initial schema

Revision ID: d080a972dfe8
Revises: 
Create Date: 2026-08-13 23:27:16.236212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd080a972dfe8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_audit',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_reference', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_audit_action'), 'backup_audit', ['action'], unique=False)
    op.create_index('ix_backup_audit_actor', 'backup_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_backup_audit_actor_id'), 'backup_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_backup_audit_occurred_at'), 'backup_audit', ['occurred_at'], unique=False)
    op.create_index('ix_backup_audit_time', 'backup_audit', ['occurred_at'], unique=False)
    op.create_table('backup_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_report_kind', 'backup_reports', ['kind'], unique=False)
    op.create_index('ix_backup_report_status', 'backup_reports', ['status'], unique=False)
    op.create_index(op.f('ix_backup_reports_kind'), 'backup_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_backup_reports_status'), 'backup_reports', ['status'], unique=False)
    op.create_table('backup_retention',
    sa.Column('target_kind', sa.String(length=32), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('archive_after_days', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_purged_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'target_kind', 'environment', name='uq_backup_retention_scope')
    )
    op.create_index(op.f('ix_backup_retention_target_kind'), 'backup_retention', ['target_kind'], unique=False)
    op.create_table('backup_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('bytes_backed_up', sa.BigInteger(), nullable=False),
    sa.Column('restore_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('restore_jobs_failed', sa.Integer(), nullable=False),
    sa.Column('mean_restore_duration_ms', sa.Float(), nullable=True),
    sa.Column('replication_jobs_lagging', sa.Integer(), nullable=False),
    sa.Column('mean_replication_lag_seconds', sa.Float(), nullable=True),
    sa.Column('storage_consumed_bytes', sa.BigInteger(), nullable=True),
    sa.Column('rpo_compliant_count', sa.Integer(), nullable=False),
    sa.Column('rpo_violated_count', sa.Integer(), nullable=False),
    sa.Column('rto_compliant_count', sa.Integer(), nullable=False),
    sa.Column('rto_violated_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_backup_statistic_window')
    )
    op.create_index('ix_backup_statistic_window', 'backup_statistics', ['window_start'], unique=False)
    op.create_index(op.f('ix_backup_statistics_window_start'), 'backup_statistics', ['window_start'], unique=False)
    op.create_table('backup_targets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('connection_ref', sa.String(length=512), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backup_status', sa.String(length=16), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_backup_target_name')
    )
    op.create_index('ix_backup_target_kind', 'backup_targets', ['target_kind'], unique=False)
    op.create_index(op.f('ix_backup_targets_is_enabled'), 'backup_targets', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_backup_targets_name'), 'backup_targets', ['name'], unique=False)
    op.create_index(op.f('ix_backup_targets_target_kind'), 'backup_targets', ['target_kind'], unique=False)
    op.create_table('dr_plans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('rto_minutes', sa.Integer(), nullable=False),
    sa.Column('recovery_groups', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dr_plan_status', 'dr_plans', ['status'], unique=False)
    op.create_index(op.f('ix_dr_plans_name'), 'dr_plans', ['name'], unique=False)
    op.create_index(op.f('ix_dr_plans_status'), 'dr_plans', ['status'], unique=False)
    op.create_table('backup_schedules',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('backup_type', sa.String(length=24), nullable=False),
    sa.Column('consistency_level', sa.String(length=24), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_schedule_target', 'backup_schedules', ['target_id'], unique=False)
    op.create_index(op.f('ix_backup_schedules_is_enabled'), 'backup_schedules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_backup_schedules_next_run_at'), 'backup_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_backup_schedules_target_id'), 'backup_schedules', ['target_id'], unique=False)
    op.create_table('dr_tests',
    sa.Column('dr_plan_id', sa.Uuid(), nullable=False),
    sa.Column('test_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('achieved_rpo_minutes', sa.Float(), nullable=True),
    sa.Column('achieved_rto_minutes', sa.Float(), nullable=True),
    sa.Column('rpo_status', sa.String(length=16), nullable=False),
    sa.Column('rto_status', sa.String(length=16), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dr_plan_id'], ['dr_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dr_test_plan', 'dr_tests', ['dr_plan_id'], unique=False)
    op.create_index('ix_dr_test_status', 'dr_tests', ['status'], unique=False)
    op.create_index(op.f('ix_dr_tests_dr_plan_id'), 'dr_tests', ['dr_plan_id'], unique=False)
    op.create_index(op.f('ix_dr_tests_status'), 'dr_tests', ['status'], unique=False)
    op.create_table('failover_events',
    sa.Column('dr_plan_id', sa.Uuid(), nullable=True),
    sa.Column('failover_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('target_ref', sa.String(length=512), nullable=True),
    sa.Column('initiated_by', sa.String(length=128), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('health_check_results', sa.JSON(), nullable=False),
    sa.Column('was_rolled_back', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dr_plan_id'], ['dr_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_failover_event_plan', 'failover_events', ['dr_plan_id'], unique=False)
    op.create_index('ix_failover_event_status', 'failover_events', ['status'], unique=False)
    op.create_index(op.f('ix_failover_events_dr_plan_id'), 'failover_events', ['dr_plan_id'], unique=False)
    op.create_index(op.f('ix_failover_events_status'), 'failover_events', ['status'], unique=False)
    op.create_table('replication_jobs',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('destination_ref', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lag_seconds', sa.Float(), nullable=True),
    sa.Column('bandwidth_limit_mbps', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replication_job_status', 'replication_jobs', ['status'], unique=False)
    op.create_index('ix_replication_job_target', 'replication_jobs', ['target_id'], unique=False)
    op.create_index(op.f('ix_replication_jobs_status'), 'replication_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_replication_jobs_target_id'), 'replication_jobs', ['target_id'], unique=False)
    op.create_table('backup_jobs',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('backup_type', sa.String(length=24), nullable=False),
    sa.Column('consistency_level', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('compressed_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('checksum_algorithm', sa.String(length=16), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_key_ref', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['backup_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['backup_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_job_started', 'backup_jobs', ['started_at'], unique=False)
    op.create_index('ix_backup_job_status', 'backup_jobs', ['status'], unique=False)
    op.create_index('ix_backup_job_target', 'backup_jobs', ['target_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_parent_job_id'), 'backup_jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_schedule_id'), 'backup_jobs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_status'), 'backup_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_backup_jobs_target_id'), 'backup_jobs', ['target_id'], unique=False)
    op.create_table('recovery_reports',
    sa.Column('dr_test_id', sa.Uuid(), nullable=True),
    sa.Column('failover_event_id', sa.Uuid(), nullable=True),
    sa.Column('rpo_target_minutes', sa.Integer(), nullable=True),
    sa.Column('rpo_achieved_minutes', sa.Float(), nullable=True),
    sa.Column('rto_target_minutes', sa.Integer(), nullable=True),
    sa.Column('rto_achieved_minutes', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dr_test_id'], ['dr_tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['failover_event_id'], ['failover_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_report_compliance', 'recovery_reports', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_recovery_reports_compliance_status'), 'recovery_reports', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_recovery_reports_dr_test_id'), 'recovery_reports', ['dr_test_id'], unique=False)
    op.create_index(op.f('ix_recovery_reports_failover_event_id'), 'recovery_reports', ['failover_event_id'], unique=False)
    op.create_table('backup_archives',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_key_ref', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('immutability_state', sa.String(length=24), nullable=False),
    sa.Column('retention_lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('legal_hold_reason', sa.String(length=512), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted_from_storage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_archive_immutability', 'backup_archives', ['immutability_state'], unique=False)
    op.create_index('ix_backup_archive_job', 'backup_archives', ['job_id'], unique=False)
    op.create_index('ix_backup_archive_tier', 'backup_archives', ['tier'], unique=False)
    op.create_index(op.f('ix_backup_archives_immutability_state'), 'backup_archives', ['immutability_state'], unique=False)
    op.create_index(op.f('ix_backup_archives_job_id'), 'backup_archives', ['job_id'], unique=False)
    op.create_index(op.f('ix_backup_archives_tier'), 'backup_archives', ['tier'], unique=False)
    op.create_table('backup_snapshots',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_snapshot_expires', 'backup_snapshots', ['expires_at'], unique=False)
    op.create_index('ix_backup_snapshot_status', 'backup_snapshots', ['status'], unique=False)
    op.create_index('ix_backup_snapshot_target', 'backup_snapshots', ['target_id'], unique=False)
    op.create_index(op.f('ix_backup_snapshots_job_id'), 'backup_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_backup_snapshots_target_id'), 'backup_snapshots', ['target_id'], unique=False)
    op.create_table('backup_verifications',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('archive_id', sa.Uuid(), nullable=True),
    sa.Column('verification_kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum_expected', sa.String(length=128), nullable=True),
    sa.Column('checksum_actual', sa.String(length=128), nullable=True),
    sa.Column('sample_restore_job_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['archive_id'], ['backup_archives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_verification_job', 'backup_verifications', ['job_id'], unique=False)
    op.create_index('ix_backup_verification_status', 'backup_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_backup_verifications_job_id'), 'backup_verifications', ['job_id'], unique=False)
    op.create_index(op.f('ix_backup_verifications_status'), 'backup_verifications', ['status'], unique=False)
    op.create_table('restore_points',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('point_kind', sa.String(length=24), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_archive_id', sa.Uuid(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['source_archive_id'], ['backup_archives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restore_point_available_at', 'restore_points', ['available_at'], unique=False)
    op.create_index('ix_restore_point_target', 'restore_points', ['target_id'], unique=False)
    op.create_index(op.f('ix_restore_points_available_at'), 'restore_points', ['available_at'], unique=False)
    op.create_index(op.f('ix_restore_points_target_id'), 'restore_points', ['target_id'], unique=False)
    op.create_table('restore_jobs',
    sa.Column('source_archive_id', sa.Uuid(), nullable=True),
    sa.Column('restore_point_id', sa.Uuid(), nullable=True),
    sa.Column('restore_kind', sa.String(length=24), nullable=False),
    sa.Column('target_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['restore_point_id'], ['restore_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_archive_id'], ['backup_archives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restore_job_archive', 'restore_jobs', ['source_archive_id'], unique=False)
    op.create_index('ix_restore_job_status', 'restore_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_restore_jobs_source_archive_id'), 'restore_jobs', ['source_archive_id'], unique=False)
    op.create_index(op.f('ix_restore_jobs_status'), 'restore_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restore_jobs_status'), table_name='restore_jobs')
    op.drop_index(op.f('ix_restore_jobs_source_archive_id'), table_name='restore_jobs')
    op.drop_index('ix_restore_job_status', table_name='restore_jobs')
    op.drop_index('ix_restore_job_archive', table_name='restore_jobs')
    op.drop_table('restore_jobs')
    op.drop_index(op.f('ix_restore_points_target_id'), table_name='restore_points')
    op.drop_index(op.f('ix_restore_points_available_at'), table_name='restore_points')
    op.drop_index('ix_restore_point_target', table_name='restore_points')
    op.drop_index('ix_restore_point_available_at', table_name='restore_points')
    op.drop_table('restore_points')
    op.drop_index(op.f('ix_backup_verifications_status'), table_name='backup_verifications')
    op.drop_index(op.f('ix_backup_verifications_job_id'), table_name='backup_verifications')
    op.drop_index('ix_backup_verification_status', table_name='backup_verifications')
    op.drop_index('ix_backup_verification_job', table_name='backup_verifications')
    op.drop_table('backup_verifications')
    op.drop_index(op.f('ix_backup_snapshots_target_id'), table_name='backup_snapshots')
    op.drop_index(op.f('ix_backup_snapshots_job_id'), table_name='backup_snapshots')
    op.drop_index('ix_backup_snapshot_target', table_name='backup_snapshots')
    op.drop_index('ix_backup_snapshot_status', table_name='backup_snapshots')
    op.drop_index('ix_backup_snapshot_expires', table_name='backup_snapshots')
    op.drop_table('backup_snapshots')
    op.drop_index(op.f('ix_backup_archives_tier'), table_name='backup_archives')
    op.drop_index(op.f('ix_backup_archives_job_id'), table_name='backup_archives')
    op.drop_index(op.f('ix_backup_archives_immutability_state'), table_name='backup_archives')
    op.drop_index('ix_backup_archive_tier', table_name='backup_archives')
    op.drop_index('ix_backup_archive_job', table_name='backup_archives')
    op.drop_index('ix_backup_archive_immutability', table_name='backup_archives')
    op.drop_table('backup_archives')
    op.drop_index(op.f('ix_recovery_reports_failover_event_id'), table_name='recovery_reports')
    op.drop_index(op.f('ix_recovery_reports_dr_test_id'), table_name='recovery_reports')
    op.drop_index(op.f('ix_recovery_reports_compliance_status'), table_name='recovery_reports')
    op.drop_index('ix_recovery_report_compliance', table_name='recovery_reports')
    op.drop_table('recovery_reports')
    op.drop_index(op.f('ix_backup_jobs_target_id'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_status'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_schedule_id'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_parent_job_id'), table_name='backup_jobs')
    op.drop_index('ix_backup_job_target', table_name='backup_jobs')
    op.drop_index('ix_backup_job_status', table_name='backup_jobs')
    op.drop_index('ix_backup_job_started', table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_index(op.f('ix_replication_jobs_target_id'), table_name='replication_jobs')
    op.drop_index(op.f('ix_replication_jobs_status'), table_name='replication_jobs')
    op.drop_index('ix_replication_job_target', table_name='replication_jobs')
    op.drop_index('ix_replication_job_status', table_name='replication_jobs')
    op.drop_table('replication_jobs')
    op.drop_index(op.f('ix_failover_events_status'), table_name='failover_events')
    op.drop_index(op.f('ix_failover_events_dr_plan_id'), table_name='failover_events')
    op.drop_index('ix_failover_event_status', table_name='failover_events')
    op.drop_index('ix_failover_event_plan', table_name='failover_events')
    op.drop_table('failover_events')
    op.drop_index(op.f('ix_dr_tests_status'), table_name='dr_tests')
    op.drop_index(op.f('ix_dr_tests_dr_plan_id'), table_name='dr_tests')
    op.drop_index('ix_dr_test_status', table_name='dr_tests')
    op.drop_index('ix_dr_test_plan', table_name='dr_tests')
    op.drop_table('dr_tests')
    op.drop_index(op.f('ix_backup_schedules_target_id'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_next_run_at'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_is_enabled'), table_name='backup_schedules')
    op.drop_index('ix_backup_schedule_target', table_name='backup_schedules')
    op.drop_table('backup_schedules')
    op.drop_index(op.f('ix_dr_plans_status'), table_name='dr_plans')
    op.drop_index(op.f('ix_dr_plans_name'), table_name='dr_plans')
    op.drop_index('ix_dr_plan_status', table_name='dr_plans')
    op.drop_table('dr_plans')
    op.drop_index(op.f('ix_backup_targets_target_kind'), table_name='backup_targets')
    op.drop_index(op.f('ix_backup_targets_name'), table_name='backup_targets')
    op.drop_index(op.f('ix_backup_targets_is_enabled'), table_name='backup_targets')
    op.drop_index('ix_backup_target_kind', table_name='backup_targets')
    op.drop_table('backup_targets')
    op.drop_index(op.f('ix_backup_statistics_window_start'), table_name='backup_statistics')
    op.drop_index('ix_backup_statistic_window', table_name='backup_statistics')
    op.drop_table('backup_statistics')
    op.drop_index(op.f('ix_backup_retention_target_kind'), table_name='backup_retention')
    op.drop_table('backup_retention')
    op.drop_index(op.f('ix_backup_reports_status'), table_name='backup_reports')
    op.drop_index(op.f('ix_backup_reports_kind'), table_name='backup_reports')
    op.drop_index('ix_backup_report_status', table_name='backup_reports')
    op.drop_index('ix_backup_report_kind', table_name='backup_reports')
    op.drop_table('backup_reports')
    op.drop_index('ix_backup_audit_time', table_name='backup_audit')
    op.drop_index(op.f('ix_backup_audit_occurred_at'), table_name='backup_audit')
    op.drop_index(op.f('ix_backup_audit_actor_id'), table_name='backup_audit')
    op.drop_index('ix_backup_audit_actor', table_name='backup_audit')
    op.drop_index(op.f('ix_backup_audit_action'), table_name='backup_audit')
    op.drop_table('backup_audit')
    # ### end Alembic commands ###
