"""initial upgrade framework schema

Revision ID: fa15b9a88aa8
Revises: 
Create Date: 2026-08-17 13:14:48.640482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa15b9a88aa8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibility_matrix',
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('compatibility_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'from_version', 'to_version', 'compatibility_type', name='uq_compatibility_matrix_entry')
    )
    op.create_index(op.f('ix_compatibility_matrix_compatibility_type'), 'compatibility_matrix', ['compatibility_type'], unique=False)
    op.create_index(op.f('ix_compatibility_matrix_from_version'), 'compatibility_matrix', ['from_version'], unique=False)
    op.create_index(op.f('ix_compatibility_matrix_status'), 'compatibility_matrix', ['status'], unique=False)
    op.create_index(op.f('ix_compatibility_matrix_to_version'), 'compatibility_matrix', ['to_version'], unique=False)
    op.create_index('ix_compatibility_matrix_type', 'compatibility_matrix', ['compatibility_type'], unique=False)
    op.create_table('release_channels',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_type', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_release_channel_name')
    )
    op.create_index(op.f('ix_release_channels_channel_type'), 'release_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_release_channels_name'), 'release_channels', ['name'], unique=False)
    op.create_table('upgrade_audit',
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_audit_action'), 'upgrade_audit', ['action'], unique=False)
    op.create_index('ix_upgrade_audit_entity', 'upgrade_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_upgrade_audit_entity_id'), 'upgrade_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_upgrade_audit_occurred_at'), 'upgrade_audit', ['occurred_at'], unique=False)
    op.create_table('upgrade_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_report_kind', 'upgrade_reports', ['kind'], unique=False)
    op.create_index('ix_upgrade_report_status', 'upgrade_reports', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_reports_kind'), 'upgrade_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_upgrade_reports_status'), 'upgrade_reports', ['status'], unique=False)
    op.create_table('upgrade_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('upgrade_count', sa.Integer(), nullable=False),
    sa.Column('rollback_count', sa.Integer(), nullable=False),
    sa.Column('migration_count', sa.Integer(), nullable=False),
    sa.Column('compatibility_failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_upgrade_statistic_window')
    )
    op.create_index(op.f('ix_upgrade_statistics_window_start'), 'upgrade_statistics', ['window_start'], unique=False)
    op.create_table('release_versions',
    sa.Column('release_channel_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('artifact_ref', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['release_channel_id'], ['release_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'release_channel_id', 'version_label', name='uq_release_version_label')
    )
    op.create_index('ix_release_version_channel', 'release_versions', ['release_channel_id'], unique=False)
    op.create_index(op.f('ix_release_versions_is_current'), 'release_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_release_versions_release_channel_id'), 'release_versions', ['release_channel_id'], unique=False)
    op.create_index(op.f('ix_release_versions_released_at'), 'release_versions', ['released_at'], unique=False)
    op.create_index(op.f('ix_release_versions_version_label'), 'release_versions', ['version_label'], unique=False)
    op.create_table('upgrade_plans',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('release_channel_id', sa.Uuid(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['release_channel_id'], ['release_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_upgrade_plan_name')
    )
    op.create_index(op.f('ix_upgrade_plans_name'), 'upgrade_plans', ['name'], unique=False)
    op.create_index(op.f('ix_upgrade_plans_target_type'), 'upgrade_plans', ['target_type'], unique=False)
    op.create_table('upgrade_dependencies',
    sa.Column('upgrade_plan_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_name', sa.String(length=128), nullable=False),
    sa.Column('required_version', sa.String(length=32), nullable=False),
    sa.Column('found_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_plan_id'], ['upgrade_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_dependencies_dependency_name'), 'upgrade_dependencies', ['dependency_name'], unique=False)
    op.create_index(op.f('ix_upgrade_dependencies_status'), 'upgrade_dependencies', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_dependencies_upgrade_plan_id'), 'upgrade_dependencies', ['upgrade_plan_id'], unique=False)
    op.create_index('ix_upgrade_dependency_plan', 'upgrade_dependencies', ['upgrade_plan_id'], unique=False)
    op.create_table('upgrade_jobs',
    sa.Column('upgrade_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_plan_id'], ['upgrade_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_job_plan', 'upgrade_jobs', ['upgrade_plan_id'], unique=False)
    op.create_index('ix_upgrade_job_status', 'upgrade_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_jobs_status'), 'upgrade_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_jobs_upgrade_plan_id'), 'upgrade_jobs', ['upgrade_plan_id'], unique=False)
    op.create_table('configuration_migrations',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=256), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_configuration_migration_job', 'configuration_migrations', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_configuration_migrations_applied_at'), 'configuration_migrations', ['applied_at'], unique=False)
    op.create_index(op.f('ix_configuration_migrations_upgrade_job_id'), 'configuration_migrations', ['upgrade_job_id'], unique=False)
    op.create_table('migration_history',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('migration_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_migration_history_job', 'migration_history', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_migration_history_migration_type'), 'migration_history', ['migration_type'], unique=False)
    op.create_index('ix_migration_history_status', 'migration_history', ['status'], unique=False)
    op.create_index(op.f('ix_migration_history_upgrade_job_id'), 'migration_history', ['upgrade_job_id'], unique=False)
    op.create_table('plugin_migrations',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_migration_job', 'plugin_migrations', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_plugin_migrations_plugin_name'), 'plugin_migrations', ['plugin_name'], unique=False)
    op.create_index(op.f('ix_plugin_migrations_status'), 'plugin_migrations', ['status'], unique=False)
    op.create_index(op.f('ix_plugin_migrations_upgrade_job_id'), 'plugin_migrations', ['upgrade_job_id'], unique=False)
    op.create_table('rollback_history',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rollback_history_job', 'rollback_history', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_rollback_history_status'), 'rollback_history', ['status'], unique=False)
    op.create_index(op.f('ix_rollback_history_upgrade_job_id'), 'rollback_history', ['upgrade_job_id'], unique=False)
    op.create_table('upgrade_history',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_history_job', 'upgrade_history', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_upgrade_history_occurred_at'), 'upgrade_history', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_upgrade_history_upgrade_job_id'), 'upgrade_history', ['upgrade_job_id'], unique=False)
    op.create_table('upgrade_targets',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('target_ref', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_target_job', 'upgrade_targets', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_upgrade_targets_status'), 'upgrade_targets', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_targets_target_type'), 'upgrade_targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_upgrade_targets_upgrade_job_id'), 'upgrade_targets', ['upgrade_job_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('upgrade_job_id', sa.Uuid(), nullable=False),
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_job_id'], ['upgrade_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_result_check_type', 'verification_results', ['check_type'], unique=False)
    op.create_index('ix_verification_result_job', 'verification_results', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_verification_results_check_type'), 'verification_results', ['check_type'], unique=False)
    op.create_index(op.f('ix_verification_results_status'), 'verification_results', ['status'], unique=False)
    op.create_index(op.f('ix_verification_results_upgrade_job_id'), 'verification_results', ['upgrade_job_id'], unique=False)
    op.create_index(op.f('ix_verification_results_verified_at'), 'verification_results', ['verified_at'], unique=False)
    op.create_table('upgrade_results',
    sa.Column('upgrade_target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_target_id'], ['upgrade_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_result_target', 'upgrade_results', ['upgrade_target_id'], unique=False)
    op.create_index(op.f('ix_upgrade_results_completed_at'), 'upgrade_results', ['completed_at'], unique=False)
    op.create_index(op.f('ix_upgrade_results_status'), 'upgrade_results', ['status'], unique=False)
    op.create_index(op.f('ix_upgrade_results_upgrade_target_id'), 'upgrade_results', ['upgrade_target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrade_results_upgrade_target_id'), table_name='upgrade_results')
    op.drop_index(op.f('ix_upgrade_results_status'), table_name='upgrade_results')
    op.drop_index(op.f('ix_upgrade_results_completed_at'), table_name='upgrade_results')
    op.drop_index('ix_upgrade_result_target', table_name='upgrade_results')
    op.drop_table('upgrade_results')
    op.drop_index(op.f('ix_verification_results_verified_at'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_upgrade_job_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_status'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_check_type'), table_name='verification_results')
    op.drop_index('ix_verification_result_job', table_name='verification_results')
    op.drop_index('ix_verification_result_check_type', table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_upgrade_targets_upgrade_job_id'), table_name='upgrade_targets')
    op.drop_index(op.f('ix_upgrade_targets_target_type'), table_name='upgrade_targets')
    op.drop_index(op.f('ix_upgrade_targets_status'), table_name='upgrade_targets')
    op.drop_index('ix_upgrade_target_job', table_name='upgrade_targets')
    op.drop_table('upgrade_targets')
    op.drop_index(op.f('ix_upgrade_history_upgrade_job_id'), table_name='upgrade_history')
    op.drop_index(op.f('ix_upgrade_history_occurred_at'), table_name='upgrade_history')
    op.drop_index('ix_upgrade_history_job', table_name='upgrade_history')
    op.drop_table('upgrade_history')
    op.drop_index(op.f('ix_rollback_history_upgrade_job_id'), table_name='rollback_history')
    op.drop_index(op.f('ix_rollback_history_status'), table_name='rollback_history')
    op.drop_index('ix_rollback_history_job', table_name='rollback_history')
    op.drop_table('rollback_history')
    op.drop_index(op.f('ix_plugin_migrations_upgrade_job_id'), table_name='plugin_migrations')
    op.drop_index(op.f('ix_plugin_migrations_status'), table_name='plugin_migrations')
    op.drop_index(op.f('ix_plugin_migrations_plugin_name'), table_name='plugin_migrations')
    op.drop_index('ix_plugin_migration_job', table_name='plugin_migrations')
    op.drop_table('plugin_migrations')
    op.drop_index(op.f('ix_migration_history_upgrade_job_id'), table_name='migration_history')
    op.drop_index('ix_migration_history_status', table_name='migration_history')
    op.drop_index(op.f('ix_migration_history_migration_type'), table_name='migration_history')
    op.drop_index('ix_migration_history_job', table_name='migration_history')
    op.drop_table('migration_history')
    op.drop_index(op.f('ix_configuration_migrations_upgrade_job_id'), table_name='configuration_migrations')
    op.drop_index(op.f('ix_configuration_migrations_applied_at'), table_name='configuration_migrations')
    op.drop_index('ix_configuration_migration_job', table_name='configuration_migrations')
    op.drop_table('configuration_migrations')
    op.drop_index(op.f('ix_upgrade_jobs_upgrade_plan_id'), table_name='upgrade_jobs')
    op.drop_index(op.f('ix_upgrade_jobs_status'), table_name='upgrade_jobs')
    op.drop_index('ix_upgrade_job_status', table_name='upgrade_jobs')
    op.drop_index('ix_upgrade_job_plan', table_name='upgrade_jobs')
    op.drop_table('upgrade_jobs')
    op.drop_index('ix_upgrade_dependency_plan', table_name='upgrade_dependencies')
    op.drop_index(op.f('ix_upgrade_dependencies_upgrade_plan_id'), table_name='upgrade_dependencies')
    op.drop_index(op.f('ix_upgrade_dependencies_status'), table_name='upgrade_dependencies')
    op.drop_index(op.f('ix_upgrade_dependencies_dependency_name'), table_name='upgrade_dependencies')
    op.drop_table('upgrade_dependencies')
    op.drop_index(op.f('ix_upgrade_plans_target_type'), table_name='upgrade_plans')
    op.drop_index(op.f('ix_upgrade_plans_name'), table_name='upgrade_plans')
    op.drop_table('upgrade_plans')
    op.drop_index(op.f('ix_release_versions_version_label'), table_name='release_versions')
    op.drop_index(op.f('ix_release_versions_released_at'), table_name='release_versions')
    op.drop_index(op.f('ix_release_versions_release_channel_id'), table_name='release_versions')
    op.drop_index(op.f('ix_release_versions_is_current'), table_name='release_versions')
    op.drop_index('ix_release_version_channel', table_name='release_versions')
    op.drop_table('release_versions')
    op.drop_index(op.f('ix_upgrade_statistics_window_start'), table_name='upgrade_statistics')
    op.drop_table('upgrade_statistics')
    op.drop_index(op.f('ix_upgrade_reports_status'), table_name='upgrade_reports')
    op.drop_index(op.f('ix_upgrade_reports_kind'), table_name='upgrade_reports')
    op.drop_index('ix_upgrade_report_status', table_name='upgrade_reports')
    op.drop_index('ix_upgrade_report_kind', table_name='upgrade_reports')
    op.drop_table('upgrade_reports')
    op.drop_index(op.f('ix_upgrade_audit_occurred_at'), table_name='upgrade_audit')
    op.drop_index(op.f('ix_upgrade_audit_entity_id'), table_name='upgrade_audit')
    op.drop_index('ix_upgrade_audit_entity', table_name='upgrade_audit')
    op.drop_index(op.f('ix_upgrade_audit_action'), table_name='upgrade_audit')
    op.drop_table('upgrade_audit')
    op.drop_index(op.f('ix_release_channels_name'), table_name='release_channels')
    op.drop_index(op.f('ix_release_channels_channel_type'), table_name='release_channels')
    op.drop_table('release_channels')
    op.drop_index('ix_compatibility_matrix_type', table_name='compatibility_matrix')
    op.drop_index(op.f('ix_compatibility_matrix_to_version'), table_name='compatibility_matrix')
    op.drop_index(op.f('ix_compatibility_matrix_status'), table_name='compatibility_matrix')
    op.drop_index(op.f('ix_compatibility_matrix_from_version'), table_name='compatibility_matrix')
    op.drop_index(op.f('ix_compatibility_matrix_compatibility_type'), table_name='compatibility_matrix')
    op.drop_table('compatibility_matrix')
    # ### end Alembic commands ###
