"""initial production hardening framework schema

Revision ID: 606b5686871c
Revises: 
Create Date: 2026-08-17 17:01:06.733948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606b5686871c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_inventory',
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('issuer', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_mutual_tls', sa.Boolean(), nullable=False),
    sa.Column('is_expiring', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_inventory_expires_at'), 'certificate_inventory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_certificate_inventory_subject'), 'certificate_inventory', ['subject'], unique=False)
    op.create_table('compliance_results',
    sa.Column('framework', sa.String(length=16), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_control_id'), 'compliance_results', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_evaluated_at'), 'compliance_results', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_compliance_results_framework'), 'compliance_results', ['framework'], unique=False)
    op.create_index(op.f('ix_compliance_results_is_compliant'), 'compliance_results', ['is_compliant'], unique=False)
    op.create_table('disaster_recovery_checks',
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_recovery_checks_check_type'), 'disaster_recovery_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_checks_checked_at'), 'disaster_recovery_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_checks_status'), 'disaster_recovery_checks', ['status'], unique=False)
    op.create_table('hardening_audit',
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardening_audit_action'), 'hardening_audit', ['action'], unique=False)
    op.create_index('ix_hardening_audit_entity', 'hardening_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_hardening_audit_entity_id'), 'hardening_audit', ['entity_id'], unique=False)
    op.create_index('ix_hardening_audit_occurred_at', 'hardening_audit', ['occurred_at'], unique=False)
    op.create_table('hardening_profiles',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('benchmark', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_hardening_profile_name')
    )
    op.create_index(op.f('ix_hardening_profiles_benchmark'), 'hardening_profiles', ['benchmark'], unique=False)
    op.create_index(op.f('ix_hardening_profiles_name'), 'hardening_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_hardening_profiles_target_type'), 'hardening_profiles', ['target_type'], unique=False)
    op.create_table('hardening_reports',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('report_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hardening_report_kind', 'hardening_reports', ['kind'], unique=False)
    op.create_index('ix_hardening_report_status', 'hardening_reports', ['status'], unique=False)
    op.create_index(op.f('ix_hardening_reports_kind'), 'hardening_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_hardening_reports_status'), 'hardening_reports', ['status'], unique=False)
    op.create_table('hardening_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hardening_run_count', sa.Integer(), nullable=False),
    sa.Column('security_finding_count', sa.Integer(), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('avg_hardening_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_hardening_statistic_window')
    )
    op.create_index(op.f('ix_hardening_statistics_window_start'), 'hardening_statistics', ['window_start'], unique=False)
    op.create_table('operational_readiness',
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_readiness_check_type'), 'operational_readiness', ['check_type'], unique=False)
    op.create_index(op.f('ix_operational_readiness_checked_at'), 'operational_readiness', ['checked_at'], unique=False)
    op.create_index(op.f('ix_operational_readiness_status'), 'operational_readiness', ['status'], unique=False)
    op.create_table('production_certifications',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_certifications_name'), 'production_certifications', ['name'], unique=False)
    op.create_index(op.f('ix_production_certifications_status'), 'production_certifications', ['status'], unique=False)
    op.create_table('runtime_protection',
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_protection_detected_at'), 'runtime_protection', ['detected_at'], unique=False)
    op.create_index(op.f('ix_runtime_protection_event_type'), 'runtime_protection', ['event_type'], unique=False)
    op.create_index(op.f('ix_runtime_protection_severity'), 'runtime_protection', ['severity'], unique=False)
    op.create_table('sbom_catalog',
    sa.Column('component_name', sa.String(length=256), nullable=False),
    sa.Column('component_version', sa.String(length=64), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sbom_catalog_component_name'), 'sbom_catalog', ['component_name'], unique=False)
    op.create_index(op.f('ix_sbom_catalog_generated_at'), 'sbom_catalog', ['generated_at'], unique=False)
    op.create_table('security_findings',
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_severity'), 'security_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_security_findings_status'), 'security_findings', ['status'], unique=False)
    op.create_index(op.f('ix_security_findings_target_type'), 'security_findings', ['target_type'], unique=False)
    op.create_table('signed_artifacts',
    sa.Column('artifact_name', sa.String(length=256), nullable=False),
    sa.Column('artifact_version', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_artifacts_artifact_name'), 'signed_artifacts', ['artifact_name'], unique=False)
    op.create_index(op.f('ix_signed_artifacts_signed_at'), 'signed_artifacts', ['signed_at'], unique=False)
    op.create_table('vulnerability_scans',
    sa.Column('scan_type', sa.String(length=16), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('package_name', sa.String(length=256), nullable=False),
    sa.Column('package_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_scans_scan_type'), 'vulnerability_scans', ['scan_type'], unique=False)
    op.create_index(op.f('ix_vulnerability_scans_severity'), 'vulnerability_scans', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerability_scans_status'), 'vulnerability_scans', ['status'], unique=False)
    op.create_table('hardening_runs',
    sa.Column('hardening_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hardening_profile_id'], ['hardening_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hardening_run_profile', 'hardening_runs', ['hardening_profile_id'], unique=False)
    op.create_index('ix_hardening_run_status', 'hardening_runs', ['status'], unique=False)
    op.create_index(op.f('ix_hardening_runs_hardening_profile_id'), 'hardening_runs', ['hardening_profile_id'], unique=False)
    op.create_index(op.f('ix_hardening_runs_status'), 'hardening_runs', ['status'], unique=False)
    op.create_table('hardening_results',
    sa.Column('hardening_run_id', sa.Uuid(), nullable=False),
    sa.Column('check_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hardening_run_id'], ['hardening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hardening_result_run', 'hardening_results', ['hardening_run_id'], unique=False)
    op.create_index(op.f('ix_hardening_results_check_name'), 'hardening_results', ['check_name'], unique=False)
    op.create_index(op.f('ix_hardening_results_hardening_run_id'), 'hardening_results', ['hardening_run_id'], unique=False)
    op.create_index(op.f('ix_hardening_results_status'), 'hardening_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hardening_results_status'), table_name='hardening_results')
    op.drop_index(op.f('ix_hardening_results_hardening_run_id'), table_name='hardening_results')
    op.drop_index(op.f('ix_hardening_results_check_name'), table_name='hardening_results')
    op.drop_index('ix_hardening_result_run', table_name='hardening_results')
    op.drop_table('hardening_results')
    op.drop_index(op.f('ix_hardening_runs_status'), table_name='hardening_runs')
    op.drop_index(op.f('ix_hardening_runs_hardening_profile_id'), table_name='hardening_runs')
    op.drop_index('ix_hardening_run_status', table_name='hardening_runs')
    op.drop_index('ix_hardening_run_profile', table_name='hardening_runs')
    op.drop_table('hardening_runs')
    op.drop_index(op.f('ix_vulnerability_scans_status'), table_name='vulnerability_scans')
    op.drop_index(op.f('ix_vulnerability_scans_severity'), table_name='vulnerability_scans')
    op.drop_index(op.f('ix_vulnerability_scans_scan_type'), table_name='vulnerability_scans')
    op.drop_table('vulnerability_scans')
    op.drop_index(op.f('ix_signed_artifacts_signed_at'), table_name='signed_artifacts')
    op.drop_index(op.f('ix_signed_artifacts_artifact_name'), table_name='signed_artifacts')
    op.drop_table('signed_artifacts')
    op.drop_index(op.f('ix_security_findings_target_type'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_status'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_severity'), table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_sbom_catalog_generated_at'), table_name='sbom_catalog')
    op.drop_index(op.f('ix_sbom_catalog_component_name'), table_name='sbom_catalog')
    op.drop_table('sbom_catalog')
    op.drop_index(op.f('ix_runtime_protection_severity'), table_name='runtime_protection')
    op.drop_index(op.f('ix_runtime_protection_event_type'), table_name='runtime_protection')
    op.drop_index(op.f('ix_runtime_protection_detected_at'), table_name='runtime_protection')
    op.drop_table('runtime_protection')
    op.drop_index(op.f('ix_production_certifications_status'), table_name='production_certifications')
    op.drop_index(op.f('ix_production_certifications_name'), table_name='production_certifications')
    op.drop_table('production_certifications')
    op.drop_index(op.f('ix_operational_readiness_status'), table_name='operational_readiness')
    op.drop_index(op.f('ix_operational_readiness_checked_at'), table_name='operational_readiness')
    op.drop_index(op.f('ix_operational_readiness_check_type'), table_name='operational_readiness')
    op.drop_table('operational_readiness')
    op.drop_index(op.f('ix_hardening_statistics_window_start'), table_name='hardening_statistics')
    op.drop_table('hardening_statistics')
    op.drop_index(op.f('ix_hardening_reports_status'), table_name='hardening_reports')
    op.drop_index(op.f('ix_hardening_reports_kind'), table_name='hardening_reports')
    op.drop_index('ix_hardening_report_status', table_name='hardening_reports')
    op.drop_index('ix_hardening_report_kind', table_name='hardening_reports')
    op.drop_table('hardening_reports')
    op.drop_index(op.f('ix_hardening_profiles_target_type'), table_name='hardening_profiles')
    op.drop_index(op.f('ix_hardening_profiles_name'), table_name='hardening_profiles')
    op.drop_index(op.f('ix_hardening_profiles_benchmark'), table_name='hardening_profiles')
    op.drop_table('hardening_profiles')
    op.drop_index('ix_hardening_audit_occurred_at', table_name='hardening_audit')
    op.drop_index(op.f('ix_hardening_audit_entity_id'), table_name='hardening_audit')
    op.drop_index('ix_hardening_audit_entity', table_name='hardening_audit')
    op.drop_index(op.f('ix_hardening_audit_action'), table_name='hardening_audit')
    op.drop_table('hardening_audit')
    op.drop_index(op.f('ix_disaster_recovery_checks_status'), table_name='disaster_recovery_checks')
    op.drop_index(op.f('ix_disaster_recovery_checks_checked_at'), table_name='disaster_recovery_checks')
    op.drop_index(op.f('ix_disaster_recovery_checks_check_type'), table_name='disaster_recovery_checks')
    op.drop_table('disaster_recovery_checks')
    op.drop_index(op.f('ix_compliance_results_is_compliant'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_framework'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_evaluated_at'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_control_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_certificate_inventory_subject'), table_name='certificate_inventory')
    op.drop_index(op.f('ix_certificate_inventory_expires_at'), table_name='certificate_inventory')
    op.drop_table('certificate_inventory')
    # ### end Alembic commands ###
