"""Report generation.

Like app version policy and configuration, there is no ``POST`` route
-- a report is generated by internal tooling (or, in tests, this
service directly) and only ever listed over HTTP.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from app.models.enums import ReportFormat, ReportKind, ReportStatus
from app.models.reporting import MobileReport
from app.repositories.reporting import MobileReportRepository


class ReportService:
    def __init__(self, repo: MobileReportRepository) -> None:
        self._repo = repo

    async def generate(
        self,
        organization_id: UUID,
        *,
        kind: ReportKind,
        title: str,
        period_start: datetime,
        period_end: datetime,
        row_count: int,
        report_format: ReportFormat = ReportFormat.JSON,
        now: datetime,
    ) -> MobileReport:
        return await self._repo.create(
            MobileReport(
                organization_id=organization_id,
                kind=kind,
                report_format=report_format,
                title=title,
                status=ReportStatus.COMPLETED,
                period_start=period_start,
                period_end=period_end,
                generated_at=now,
                row_count=row_count,
            )
        )


__all__ = ["ReportService"]
