"""initial public api platform schema

Revision ID: b2389ecc14db
Revises: 
Create Date: 2026-08-17 10:43:40.494365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2389ecc14db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_products',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('product_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_product_status', 'api_products', ['status'], unique=False)
    op.create_index('ix_api_product_type', 'api_products', ['product_type'], unique=False)
    op.create_index(op.f('ix_api_products_product_type'), 'api_products', ['product_type'], unique=False)
    op.create_index(op.f('ix_api_products_status'), 'api_products', ['status'], unique=False)
    op.create_table('developer_audit',
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_audit_action', 'developer_audit', ['action'], unique=False)
    op.create_index('ix_developer_audit_entity', 'developer_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_developer_audit_entity_id'), 'developer_audit', ['entity_id'], unique=False)
    op.create_index('ix_developer_audit_occurred_at', 'developer_audit', ['occurred_at'], unique=False)
    op.create_table('developer_organizations',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_organization_name', 'developer_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_developer_organizations_name'), 'developer_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_developer_organizations_status'), 'developer_organizations', ['status'], unique=False)
    op.create_table('developer_reports',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('report_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_report_kind', 'developer_reports', ['kind'], unique=False)
    op.create_index('ix_developer_report_status', 'developer_reports', ['status'], unique=False)
    op.create_index(op.f('ix_developer_reports_kind'), 'developer_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_developer_reports_status'), 'developer_reports', ['status'], unique=False)
    op.create_table('developer_statistics',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_call_count', sa.Integer(), nullable=False),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.Column('application_count', sa.Integer(), nullable=False),
    sa.Column('sdk_download_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'window_start', name='uq_developer_statistic_window')
    )
    op.create_index(op.f('ix_developer_statistics_window_start'), 'developer_statistics', ['window_start'], unique=False)
    op.create_table('api_mock_services',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_path', sa.String(length=256), nullable=False),
    sa.Column('mock_type', sa.String(length=8), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=False),
    sa.Column('simulated_latency_ms', sa.Float(), nullable=False),
    sa.Column('simulate_error', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_mock_service_product', 'api_mock_services', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_api_mock_services_api_product_id'), 'api_mock_services', ['api_product_id'], unique=False)
    op.create_table('api_plans',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('quota_per_month', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_plan_product', 'api_plans', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_api_plans_api_product_id'), 'api_plans', ['api_product_id'], unique=False)
    op.create_table('api_versions',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_breaking_change', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_version_label', 'api_versions', ['version_label'], unique=False)
    op.create_index('ix_api_version_product', 'api_versions', ['api_product_id'], unique=False)
    op.create_index('ix_api_version_status', 'api_versions', ['status'], unique=False)
    op.create_index(op.f('ix_api_versions_api_product_id'), 'api_versions', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_api_versions_status'), 'api_versions', ['status'], unique=False)
    op.create_index(op.f('ix_api_versions_version_label'), 'api_versions', ['version_label'], unique=False)
    op.create_table('developer_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('developer_organization_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['developer_organization_id'], ['developer_organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_account_status', 'developer_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_developer_accounts_email'), 'developer_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_developer_accounts_status'), 'developer_accounts', ['status'], unique=False)
    op.create_table('api_changelog',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('api_version_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_breaking', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_changelog_api_product_id'), 'api_changelog', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_api_changelog_api_version_id'), 'api_changelog', ['api_version_id'], unique=False)
    op.create_index('ix_api_changelog_product', 'api_changelog', ['api_product_id'], unique=False)
    op.create_table('api_quotas',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('quota_type', sa.String(length=16), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('used_value', sa.Integer(), nullable=False),
    sa.Column('reset_policy', sa.String(length=8), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_quota_developer', 'api_quotas', ['developer_account_id'], unique=False)
    op.create_index('ix_api_quota_type', 'api_quotas', ['quota_type'], unique=False)
    op.create_index(op.f('ix_api_quotas_developer_account_id'), 'api_quotas', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_api_quotas_period_end'), 'api_quotas', ['period_end'], unique=False)
    op.create_index(op.f('ix_api_quotas_quota_type'), 'api_quotas', ['quota_type'], unique=False)
    op.create_table('api_rate_limits',
    sa.Column('api_plan_id', sa.Uuid(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('burst_limit', sa.Integer(), nullable=False),
    sa.Column('concurrent_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_plan_id'], ['api_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_rate_limit_plan', 'api_rate_limits', ['api_plan_id'], unique=False)
    op.create_index(op.f('ix_api_rate_limits_api_plan_id'), 'api_rate_limits', ['api_plan_id'], unique=True)
    op.create_table('api_sandbox',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sandbox_api_product_id'), 'api_sandbox', ['api_product_id'], unique=False)
    op.create_index('ix_api_sandbox_developer', 'api_sandbox', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_api_sandbox_developer_account_id'), 'api_sandbox', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_api_sandbox_status'), 'api_sandbox', ['status'], unique=False)
    op.create_table('api_subscriptions',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('api_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_plan_id'], ['api_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_subscription_developer', 'api_subscriptions', ['developer_account_id'], unique=False)
    op.create_index('ix_api_subscription_status', 'api_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_api_subscriptions_api_plan_id'), 'api_subscriptions', ['api_plan_id'], unique=False)
    op.create_index(op.f('ix_api_subscriptions_developer_account_id'), 'api_subscriptions', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_api_subscriptions_status'), 'api_subscriptions', ['status'], unique=False)
    op.create_table('developer_applications',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('allowed_origins', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_developer_application_status', 'developer_applications', ['status'], unique=False)
    op.create_index(op.f('ix_developer_applications_developer_account_id'), 'developer_applications', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_developer_applications_status'), 'developer_applications', ['status'], unique=False)
    op.create_table('graphql_schemas',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('api_version_id', sa.Uuid(), nullable=False),
    sa.Column('schema_sdl', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graphql_schema_product', 'graphql_schemas', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_graphql_schemas_api_product_id'), 'graphql_schemas', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_graphql_schemas_api_version_id'), 'graphql_schemas', ['api_version_id'], unique=False)
    op.create_table('openapi_documents',
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('api_version_id', sa.Uuid(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_version_id'], ['api_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_openapi_document_product', 'openapi_documents', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_openapi_documents_api_product_id'), 'openapi_documents', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_openapi_documents_api_version_id'), 'openapi_documents', ['api_version_id'], unique=False)
    op.create_table('personal_access_tokens',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pat_status', 'personal_access_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_developer_account_id'), 'personal_access_tokens', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_expires_at'), 'personal_access_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_status'), 'personal_access_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_table('api_keys',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['developer_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_key_status', 'api_keys', ['status'], unique=False)
    op.create_index(op.f('ix_api_keys_application_id'), 'api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_table('api_usage',
    sa.Column('developer_account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('api_product_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_id'], ['developer_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_account_id'], ['developer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_api_product_id'), 'api_usage', ['api_product_id'], unique=False)
    op.create_index('ix_api_usage_application', 'api_usage', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_usage_application_id'), 'api_usage', ['application_id'], unique=False)
    op.create_index('ix_api_usage_developer', 'api_usage', ['developer_account_id'], unique=False)
    op.create_index(op.f('ix_api_usage_developer_account_id'), 'api_usage', ['developer_account_id'], unique=False)
    op.create_index('ix_api_usage_occurred_at', 'api_usage', ['occurred_at'], unique=False)
    op.create_table('application_credentials',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['developer_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_credential_status', 'application_credentials', ['status'], unique=False)
    op.create_index(op.f('ix_application_credentials_application_id'), 'application_credentials', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_credentials_client_id'), 'application_credentials', ['client_id'], unique=True)
    op.create_index(op.f('ix_application_credentials_status'), 'application_credentials', ['status'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('grant_types', sa.JSON(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['developer_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_client_status', 'oauth_clients', ['status'], unique=False)
    op.create_index(op.f('ix_oauth_clients_application_id'), 'oauth_clients', ['application_id'], unique=False)
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_status'), 'oauth_clients', ['status'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('oauth_client_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['oauth_client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_token_client', 'oauth_tokens', ['oauth_client_id'], unique=False)
    op.create_index('ix_oauth_token_status', 'oauth_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_expires_at'), 'oauth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_oauth_client_id'), 'oauth_tokens', ['oauth_client_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_status'), 'oauth_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_token_hash'), 'oauth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_token_type'), 'oauth_tokens', ['token_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_token_type'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_token_hash'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_status'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_oauth_client_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_expires_at'), table_name='oauth_tokens')
    op.drop_index('ix_oauth_token_status', table_name='oauth_tokens')
    op.drop_index('ix_oauth_token_client', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_oauth_clients_status'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_application_id'), table_name='oauth_clients')
    op.drop_index('ix_oauth_client_status', table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_application_credentials_status'), table_name='application_credentials')
    op.drop_index(op.f('ix_application_credentials_client_id'), table_name='application_credentials')
    op.drop_index(op.f('ix_application_credentials_application_id'), table_name='application_credentials')
    op.drop_index('ix_application_credential_status', table_name='application_credentials')
    op.drop_table('application_credentials')
    op.drop_index('ix_api_usage_occurred_at', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_developer_account_id'), table_name='api_usage')
    op.drop_index('ix_api_usage_developer', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_application_id'), table_name='api_usage')
    op.drop_index('ix_api_usage_application', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_api_product_id'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_application_id'), table_name='api_keys')
    op.drop_index('ix_api_key_status', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_status'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_expires_at'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_developer_account_id'), table_name='personal_access_tokens')
    op.drop_index('ix_pat_status', table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_index(op.f('ix_openapi_documents_api_version_id'), table_name='openapi_documents')
    op.drop_index(op.f('ix_openapi_documents_api_product_id'), table_name='openapi_documents')
    op.drop_index('ix_openapi_document_product', table_name='openapi_documents')
    op.drop_table('openapi_documents')
    op.drop_index(op.f('ix_graphql_schemas_api_version_id'), table_name='graphql_schemas')
    op.drop_index(op.f('ix_graphql_schemas_api_product_id'), table_name='graphql_schemas')
    op.drop_index('ix_graphql_schema_product', table_name='graphql_schemas')
    op.drop_table('graphql_schemas')
    op.drop_index(op.f('ix_developer_applications_status'), table_name='developer_applications')
    op.drop_index(op.f('ix_developer_applications_developer_account_id'), table_name='developer_applications')
    op.drop_index('ix_developer_application_status', table_name='developer_applications')
    op.drop_table('developer_applications')
    op.drop_index(op.f('ix_api_subscriptions_status'), table_name='api_subscriptions')
    op.drop_index(op.f('ix_api_subscriptions_developer_account_id'), table_name='api_subscriptions')
    op.drop_index(op.f('ix_api_subscriptions_api_plan_id'), table_name='api_subscriptions')
    op.drop_index('ix_api_subscription_status', table_name='api_subscriptions')
    op.drop_index('ix_api_subscription_developer', table_name='api_subscriptions')
    op.drop_table('api_subscriptions')
    op.drop_index(op.f('ix_api_sandbox_status'), table_name='api_sandbox')
    op.drop_index(op.f('ix_api_sandbox_developer_account_id'), table_name='api_sandbox')
    op.drop_index('ix_api_sandbox_developer', table_name='api_sandbox')
    op.drop_index(op.f('ix_api_sandbox_api_product_id'), table_name='api_sandbox')
    op.drop_table('api_sandbox')
    op.drop_index(op.f('ix_api_rate_limits_api_plan_id'), table_name='api_rate_limits')
    op.drop_index('ix_api_rate_limit_plan', table_name='api_rate_limits')
    op.drop_table('api_rate_limits')
    op.drop_index(op.f('ix_api_quotas_quota_type'), table_name='api_quotas')
    op.drop_index(op.f('ix_api_quotas_period_end'), table_name='api_quotas')
    op.drop_index(op.f('ix_api_quotas_developer_account_id'), table_name='api_quotas')
    op.drop_index('ix_api_quota_type', table_name='api_quotas')
    op.drop_index('ix_api_quota_developer', table_name='api_quotas')
    op.drop_table('api_quotas')
    op.drop_index('ix_api_changelog_product', table_name='api_changelog')
    op.drop_index(op.f('ix_api_changelog_api_version_id'), table_name='api_changelog')
    op.drop_index(op.f('ix_api_changelog_api_product_id'), table_name='api_changelog')
    op.drop_table('api_changelog')
    op.drop_index(op.f('ix_developer_accounts_status'), table_name='developer_accounts')
    op.drop_index(op.f('ix_developer_accounts_email'), table_name='developer_accounts')
    op.drop_index('ix_developer_account_status', table_name='developer_accounts')
    op.drop_table('developer_accounts')
    op.drop_index(op.f('ix_api_versions_version_label'), table_name='api_versions')
    op.drop_index(op.f('ix_api_versions_status'), table_name='api_versions')
    op.drop_index(op.f('ix_api_versions_api_product_id'), table_name='api_versions')
    op.drop_index('ix_api_version_status', table_name='api_versions')
    op.drop_index('ix_api_version_product', table_name='api_versions')
    op.drop_index('ix_api_version_label', table_name='api_versions')
    op.drop_table('api_versions')
    op.drop_index(op.f('ix_api_plans_api_product_id'), table_name='api_plans')
    op.drop_index('ix_api_plan_product', table_name='api_plans')
    op.drop_table('api_plans')
    op.drop_index(op.f('ix_api_mock_services_api_product_id'), table_name='api_mock_services')
    op.drop_index('ix_api_mock_service_product', table_name='api_mock_services')
    op.drop_table('api_mock_services')
    op.drop_index(op.f('ix_developer_statistics_window_start'), table_name='developer_statistics')
    op.drop_table('developer_statistics')
    op.drop_index(op.f('ix_developer_reports_status'), table_name='developer_reports')
    op.drop_index(op.f('ix_developer_reports_kind'), table_name='developer_reports')
    op.drop_index('ix_developer_report_status', table_name='developer_reports')
    op.drop_index('ix_developer_report_kind', table_name='developer_reports')
    op.drop_table('developer_reports')
    op.drop_index(op.f('ix_developer_organizations_status'), table_name='developer_organizations')
    op.drop_index(op.f('ix_developer_organizations_name'), table_name='developer_organizations')
    op.drop_index('ix_developer_organization_name', table_name='developer_organizations')
    op.drop_table('developer_organizations')
    op.drop_index('ix_developer_audit_occurred_at', table_name='developer_audit')
    op.drop_index(op.f('ix_developer_audit_entity_id'), table_name='developer_audit')
    op.drop_index('ix_developer_audit_entity', table_name='developer_audit')
    op.drop_index('ix_developer_audit_action', table_name='developer_audit')
    op.drop_table('developer_audit')
    op.drop_index(op.f('ix_api_products_status'), table_name='api_products')
    op.drop_index(op.f('ix_api_products_product_type'), table_name='api_products')
    op.drop_index('ix_api_product_type', table_name='api_products')
    op.drop_index('ix_api_product_status', table_name='api_products')
    op.drop_table('api_products')
    # ### end Alembic commands ###
